### ISSUE TITLE
[1.19] Exception error thrown if more than 23 mods loaded.

### ISSUE THREAD

**Issue by Baggytrousers27** [Majrusz/MajruszsProgressiveDifficultyMod#102]
Forge 41.1.0
majrusz-library-1.19-2.12.0
majruszs-difficulty-1.19-1.5.6
Any 23+ mods (Aside from the 2 that make up forge which make 25)

java.lang.reflect.InvocationTargetException
java.lang.ExceptionInInitializerError

[Debug log with 23 mods](https://pastebin.com/tg8ryi9W)
[Debug log with 24 mods](https://pastebin.com/nYzHCX9u)
[crashlog](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/9195465/crash-2022-07-27_15.59.39-fml.txt)

Also hooray for a stable (touch wood) build of forge ...

**Comment by Majrusz** [comment]
Thanks for the report, it should be fixed now d909927fa0d7bb31a17c4e4240f9f43a7c8e5bc7
