### ISSUE TITLE
Animals stuck in dying animation

### ISSUE THREAD

**Issue by TheWookofWallST** [Majrusz/MajruszsProgressiveDifficultyMod#103]
**Describe the bug**
On my server with your mod on it i keep running into snakes and turtles and other small animals from Untamed Wilds that are stuck getting damage, they are still moving around but they are red and stuck between dying animations 

**Steps To Reproduce**
I've restarted my server seems to be only happening to small UntamedWild animals only started happening when I added your mod and stopped when I removed it.

**Screenshots**
![2022-07-29_20 23 19](https://user-images.githubusercontent.com/68366143/181864968-fa9416e3-fd56-48af-85b5-80594e2c3578.png)

**Version (please complete the following information):**
 - Minecraft version: 1.18.2
 - Version of the mod: 1.4.3
 - Additional mods: 
 - UntamedWilds + Progressive Difficulty issue but I have many mods
[modlist.txt](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/9224096/modlist.txt)

**Comment by TheWookofWallST** [comment]
I've started noticing it on other mobs like the pillagers as well so I think it is just any mob. Maybe something to do with the bleeding

**Comment by Majrusz** [comment]
Gonna work on this bug as soon as I backport the latest 1.19.1 release to 1.18.2 (probably by the end of next week it should be fixed)

**Comment by TheWookofWallST** [comment]
Okay that's awesome! I loved this mod so i was disappointed i had to remove it from my modpack. Super glad you not only started working on it fast but are gonna fix and backport! You've earned a new fan

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Majrusz** [comment]
Thanks for the report, fixed in the latest 1.4.4 release
