### ISSUE TITLE
Sound are down and undead bar freez

### ISSUE THREAD

**Issue by HINPRAY** [Majrusz/MajruszsProgressiveDifficultyMod#106]
Hello, want to thank you for your cool mod first. Back to issue.

I'v been in underground, killing zombies from spawner and waves of undead army is started.
I go back to surface and starting to defend myself. I dunno why but some of minecraft sounds are down, and the same time undead bar are frezzed. First i thought they are stuck somewhere, tried to find almost 1 hour, no result.

**Comment by Majrusz** [comment]
Fixed 605d21bda923af345adaafa2c76306989ac0d2e2, gonna update my mod soon
