### ISSUE TITLE
Crash on startup 

### ISSUE THREAD

**Issue by xelotex** [Majrusz/MajruszsProgressiveDifficultyMod#107]
it makes my game crash on startup and i have the version 1.4.4 of the mod, and the 2.7.3 version of the library installed, doesn't leave any crash reports.

**Comment by Majrusz** [comment]
What forge version do you use? I cannot reproduce this crash on forge 40.1.69

**Comment by xelotex** [comment]
> What forge version do you use? I cannot reproduce this crash on forge 40.1.69

i use the same version of forge, if you want i can make a link to give you my modpack, and maybe then you can reproduce the crash, sounds good?.

**Comment by xelotex** [comment]
https://mega.nz/file/NItHGTyC#Mvu-O7MVqgPB6zfJ9V-_30S4AbQHHZgx7xfSUNEyISI

**Comment by Majrusz** [comment]
![image](https://user-images.githubusercontent.com/57394914/183114752-cae77a52-7444-4be5-807f-e9d3517fbc00.png)
Amazing that I am able to run the game easily 😢 Can you provide me a debug log after starting the game? It is located there: **_%appdata%/.minecraft/logs/debug.log_**

**Comment by xelotex** [comment]
i guess that you copied the config files too right?

**Comment by xelotex** [comment]
[2022-08-05-4.log.gz](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/9270601/2022-08-05-4.log.gz)

**Comment by xelotex** [comment]
godamn i'm stupid, i'm so sorry dude is my bad, something is wrong with the forge installer and it gives me and error, it says: "Failed to download version manifest, can not find client jar URL." i have checked the versions folder and everything seems to be right installed, so idk, i guess its because of that URL thing, so yeah is a forge issue not yours, sorry.

I SOLVED IT: basically this error was happening because i had and obsolete version of java.
