### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by xelotex** [Majrusz/MajruszsProgressiveDifficultyMod#108]
[crash-2022-08-07_15.19.43-client.txt](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/9277602/crash-2022-08-07_15.19.43-client.txt)

This happened while i was fighting an undead army, i was using noteenough crashes mod so it send me to the main manu, and i could re enter the world, when i did that everything was really glitchy, there was invisible mobs and a lot of textures where like "swapped", between objects, for example: a diamond sword having a the golden carrot texture, couldn't get a screenshot sadly.

**Comment by Majrusz** [comment]
Fixed c0062b88ddac92122b94879e7b21bef769206eb0, thanks for the report
