### ISSUE TITLE
[1.18.2] Golden Bandages don't give different effects to normal Bandages

### ISSUE THREAD

**Issue by java-jambalaya** [Majrusz/MajruszsProgressiveDifficultyMod#109]
Golden Bandages appear to be bugged, giving the player the same effects as normal Bandages do when used, regardless of what is set in the Golden Bandage config (my guess is that they're both using the normal Bandage config), thus giving only a few seconds of Regeneration I and no Bleeding Immunity.

**Comment by Majrusz** [comment]
Hi, maybe there is a compatibility bug because I tested that on both 1.18.2 and 1.19.1 and it works properly 
![image](https://user-images.githubusercontent.com/57394914/184011561-92c67fc7-e45d-4e42-984c-fda06c7187fb.png)

**Comment by Majrusz** [comment]
Can you try to reproduce that with just my mod?

**Comment by java-jambalaya** [comment]
Yes, it seems a bit more complicated to replicate that I initially realised, but here's the method I came up with to do it reliably:

- Create new world of game mode **creative** (cheats on)
- Load in
- Change gamemode to survival (I used F3+F4 to do this)
- Give yourself a golden bandage (I used JEI)
- Use it

It seems its something to do with swapping gamemodes that causes the issue? Probably one of the strangest bugs I've seen but hopefully this helps diagnose the issue.

**Comment by Majrusz** [comment]
Unfortunately I cannot reproduce this bug

**Comment by java-jambalaya** [comment]
I'm running the latest Forge version (40.1.73) if that could affect it? Otherwise I'm not sure

**Comment by java-jambalaya** [comment]
I've also found an easier way of replicating, which is by creating a new world in survival with cheats on, running `/give @p majruszsdifficulty:golden_bandage`, and using it.
If you then swap gamemodes to creative however, the golden bandages work as intended,

**Comment by Majrusz** [comment]
Wow, now I can reproduce that and it actually does not work on both 1.18.2 and 1.19.2. Thanks for the report, gonna work on it soon

**Comment by Majrusz** [comment]
Also fixed 671042224af2ac441db7a39a95107df53c61264a, gonna update my mod soon
