### ISSUE TITLE
Option to adjust difficulty advancement rate

### ISSUE THREAD

**Issue by RuneOracle** [Majrusz/MajruszsProgressiveDifficultyMod#111]
Playing this on a server makes for disadvantages for those who don't play enough after the initial launch, is there some kind of option, config, or command to slow down the rate at which difficulty advances?

**Comment by Majrusz** [comment]
Hi, it is not possible at the moment, and it was already requested https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/issues/72
