### ISSUE TITLE
[1.19.2 Forge] Startup Crash with modpack

### ISSUE THREAD

**Issue by RedBeast1959** [Majrusz/MajruszsProgressiveDifficultyMod#113]
Forge 43.1.43
majruszs-difficulty-1.19.2-1.5.11.jar
majrusz-library-1.19.2-2.15.1.jar

Crash report:
[crash-2022-10-16_22.34.16-fml.txt](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/9794705/crash-2022-10-16_22.34.16-fml.txt)

lastest.log
[latest.log](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/9794708/latest.log)

**Comment by Majrusz** [comment]
Thanks for the report, it should be fixed in the next 1.6.0 release 91f78c7783c51e693231c929961ffed5768eb0e8
