### ISSUE TITLE
End Remastered 1.18.2 (fabric) isn't working

### ISSUE THREAD

**Issue by ySunset** [Majrusz/MajruszsProgressiveDifficultyMod#114]
I made an rpg modpack to play, and I put the "end remastered" in this modpack, however, this mod is not working, it does not generate structures, it does not have the crystals for the armor, there is no way to buy the castle map from the cartographer .

I did tests on other versions and realized that only 1.16.5 and below is working correctly, above that the mod doesn't work as it should

It's worth mentioning that the modpack is entirely in FABRIC, and the tests I did involved both versions, both fabric and forge don't work if you're playing 1.17 and up
![imagem_2022-11-09_103948572](https://user-images.githubusercontent.com/117833742/200844943-acdcaaee-4eac-4403-8499-55727f65194e.png)

these are the mods i have, and as far as i know, there are no conflicts between them

**Comment by Majrusz** [comment]
Hi, sorry, but my mod is only supported on forge and I wont work on a fix for that :(
