### ISSUE TITLE
[1.19.2] Having this mod messes up the sprint FOV for boats

### ISSUE THREAD

**Issue by BugmanBugman** [Majrusz/MajruszsProgressiveDifficultyMod#115]
Title. When you try to sprint in a boat with the mod, the FOV change shorts out and doesn't work

**Comment by Majrusz** [comment]
Hi, thanks for the report in the next update 1.6.0 it will be fixed. Silly but it was related to Undead Set and once I reworked it is not an issue anymore 4f091d03bcdebb099c1d685f1188bf02b0a548e6
