### ISSUE TITLE
[1.18.2 | Question] Is it possible to add more difficulty stages?

### ISSUE THREAD

**Issue by KeithLerner** [Majrusz/MajruszsProgressiveDifficultyMod#116]
I'm building a big mod pack for my friends and I and was wondering If I can add a peaceful stage and maybe an easy stage before the normal stage by configuring the mod differently or making an add-on mod. I'm also curious about the ability to hook in content from other mods, like defeating a boss from the twilight forest mod for example.

**Comment by Majrusz** [comment]
Hi, unfortunately it is not possible to add more stages, but you can adjust which mobs starts existing one. For instance you can replace the Ender Dragon with any boss from Twilight Forest to start the Master Mode in the configuration file

**Comment by KeithLerner** [comment]
got it! thanks for the quick response!

**Comment by Majrusz** [comment]
You're welcome!
