### ISSUE TITLE
Undead Army Raid

### ISSUE THREAD

**Issue by seanxiecn** [Majrusz/MajruszsProgressiveDifficultyMod#117]
Mod version:1.5.11
Library version:2.17.0
Forge version:43.1.52

The process of the raid often gets stuck, I'm sure I killed all the undeads and checked it with command.
![2022-11-16_16 48 23](https://user-images.githubusercontent.com/76879847/202974013-6dd7b81a-97f8-4475-be27-1e6ea1a64063.png)

**Comment by seanxiecn** [comment]
I'm sorry to point out but It is really annoying

**Comment by Majrusz** [comment]
Hi, no need to sorry, thanks for the report! I am working on it and in the next 1.6.0 update it should be fixed

**Comment by Majrusz** [comment]
Yup, it has been fixed and in the next 1.6.0 release it wont be an issue anymore, thanks anyway 👍
