### ISSUE TITLE
[Bug] If you start an Undead raid to high it cannot be completed

### ISSUE THREAD

**Issue by ElTioYisus** [Majrusz/MajruszsProgressiveDifficultyMod#118]
I was buillding a village with the MCA mod at the 220 high above an ocean, because undeads started spawning around me up there, an undead raid started, but all mobs started to aproach on ocean surface normally with frost walk boots, i went down there but the distance count as i was to far from the raid, i killed the first raid but when i went up again the raid still was showing without mobs to kill and i had to uninstall the mod for a moment for the raid to dissapear (I tried deactivating undead raid it but it didnt work).

**Comment by ElTioYisus** [comment]
1.18.2 version

**Comment by ElTioYisus** [comment]
reinstalled the mod and the raid showed again, is there a way to end a raid through commands?

**Comment by ElTioYisus** [comment]
I solved it starting another raid closer to the ocean

**Comment by Majrusz** [comment]
It should be fixed by now, there was a bug in older versions where mobs could not spawn at all but count towards the progress
