### ISSUE TITLE
Missing enemy in the Undead raid 

### ISSUE THREAD

**Issue by Pinkhai** [Majrusz/MajruszsProgressiveDifficultyMod#119]
minecraft1.18.2 mod 1.4.4
Each time when I start an Undead raid , the last 20 percent of mobs will missing. presented as the line of progress will have 20 percent left but no enemy alive nearby. (I have tested in the Superflat). sometime I can end the 1st wave, but It happens in 2nd wave either. so that I can not end the undead raid.
your mod is nice I think this issue will help you make it better.

**Comment by Majrusz** [comment]
Thanks for the report, it was fixed with the latest 1.6.1 backport
