### ISSUE TITLE
[Bug] Cursed Armor Doesn't Attack

### ISSUE THREAD

**Issue by INooBTooMuch** [Majrusz/MajruszsProgressiveDifficultyMod#121]
I opened a chest from a ruined portal and it spawned a Cursed Armor but it didn't attack me. (I also tested it by spawning it with the egg). They also seem to burn.

Minecarft : 1.18.2
Forge : 40.2.0
Progressive Difficulty : 1.6.1

**Comment by Majrusz** [comment]
Hi, it has been fixed in 1.7.0 and this version is now available
