### ISSUE TITLE
Naturally spawned mobs with Undead Army Armors are not despawning, piling up and lag the game.

### ISSUE THREAD

**Issue by zlainsama** [Majrusz/MajruszsProgressiveDifficultyMod#124]
I was staying in an area, setting up a base and trying to clear a dungeon.
While doing so, I noticed my game starts to have TPS lag, then I opened F3, found out 900+ entities in the area.
Then I tried to move away from the area, didn't work, when I'm back in the area, entity counter is still 900+.
After that, I used freecam mod to check, there are lots of undead army armor equipped mobs(husks, strays, zombies, skeletons) everywhere underground.
Lastly, I used nbteditor tool to check the save, those mobs are all tagged with PersistenceRequired.

Version: majruszs-difficulty-1.19.2-1.6.1

**Comment by Majrusz** [comment]
Hi, thanks for the report, soon version 1.7.0 will be available with proper fix included. I will keep the issue open until I release that version

**Comment by Majrusz** [comment]
Hi, it has been fixed in 1.7.0 so I close the report
