### ISSUE TITLE
Zombies and Skeleton Groups spawned by the mod causing TPS lag

### ISSUE THREAD

**Issue by Creepercharge** [Majrusz/MajruszsProgressiveDifficultyMod#125]
Zombies and skeletons spawned by the mod are causing significant TPS lag. Both spark and observable are showing both types of mobs taking up much of the server tick time. Might be tied into the other issue #124 where mobs with undead army armor doesn't despawn.

Mod version: **majruszs-difficulty-1.18.2-1.6.1**

**Comment by garlandttv** [comment]
Same Issue here

**Comment by ericrecke** [comment]
same here, there's an spot of 300 zombies, 200 skeletons in a small 3x3 block

**Comment by Majrusz** [comment]
Hi, yeah it is related to https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/issues/124, and soon it will be fixed in the next major update (1.7.0)

**Comment by Majrusz** [comment]
Hi, so it has been fixed in 1.7.0 but if you still encounter any issues, feel free to reopen the report
