### ISSUE TITLE
[1.19.2] crash when joining server on latest version

### ISSUE THREAD

**Issue by genesy** [Majrusz/MajruszsProgressiveDifficultyMod#126]
[crash-2023-03-04_01.24.04-client.txt](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/10884721/crash-2023-03-04_01.24.04-client.txt)
crash when joining server on newest version

**Comment by genesy** [comment]
it works on single player and the server didn't crash either but joining is crashing.

**Comment by Davokushi** [comment]
Same

**Comment by Majrusz** [comment]
Hi, thanks for the report and it has been fixed in 1.7.1 release
