### ISSUE TITLE
[1.19.2] Cursed Armour doesn't move or react to anything when certain other mods modify mob ai

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [Majrusz/MajruszsProgressiveDifficultyMod#128]
Majrusz's Library: 3.2.0
Majrusz's difficulty: 1.7.1
Quark: 3.4-393
AutoRegLib: 1.8.2-55
Forge: 43.2.6
Minecraft: 1.19.2

Latest Log: https://gist.github.com/NJL5390/45b5ecd15d0641e42f2d29aba67c149c

Hello,

I have come across an issue lately in regards to the cursed armour mob that was added recently. This issue involves the mob just standing still and not doing anything when it is spawned in nor reacting to anything, almost like it was spawned without any ai.
![2023-03-05_20 38 40](https://user-images.githubusercontent.com/64381954/222984781-f9589f59-f835-49aa-9210-800a134f562f.png)
![2023-03-05_20 39 38](https://user-images.githubusercontent.com/64381954/222984809-66cfc9b7-26b6-41c6-bf10-e0da24264d58.png)

This seems to be a conflict with other mods as this does not happen with Majrusz's difficulty alone. There are a couple mods I have identified  where some of their features cause this bug. For example, Quark's "Skull Pikes" feature (where mob ai is changed to run away from mob heads on fence posts) causes this bug to happen (and is the one I have used for generating the log file above).

Another example is Enhanced AI and some of the features in their "base" module such as "Shielding" and "targeting". These are the only two I have identified, but they are not the only mods that cause this issue, there are likely many more in my modpack that I have not been able to identify. Therefore I am posting this issue here as I suspect the issue is on your end since I have never had a problem with these types of mods interfering like this before.

Please let me know if you need any further information from me and I will be happy to help!

Thanks for the awesome mod!

Quark's Page: https://www.curseforge.com/minecraft/mc-mods/quark?gameCategorySlug=mc-mods&projectID=243121
Enhanced AI's Page: https://www.curseforge.com/minecraft/mc-mods/enhanced-ai

**Comment by Majrusz** [comment]
Thanks for the report, fixed in upcoming 1.7.4 release dd89fbb44357fc990eec84279e2422efc987b090 (I will keep the thread open before I release this version)

**Comment by Catomax262** [comment]
It has happened to me too, i thought it was like that

**Comment by Majrusz** [comment]
1.7.4 has been released so this should not be an issue anymore
