### ISSUE TITLE
[1.18.2] Server Crash while fighting Undead Army

### ISSUE THREAD

**Issue by Creepercharge09** [Majrusz/MajruszsProgressiveDifficultyMod#129]
Here's the crash report [crash-2023-03-06_16.59.53-server.txt](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/10900666/crash-2023-03-06_16.59.53-server.txt)
Mod version: majruszs-difficulty-1.18.2-1.7.1

**Comment by JDanielRC** [comment]
To add on this, seems like the issue occurs whenever you're fighting with a wave and start hitting mobs, happened to me with a Cerberus after 2-3 hits, immediate crash, was hitting him with a modded sword, but with no strange effects, so not likely related to it.
Could it maybe be related to how you update the raid progress when killing mobs, possibly killing a mob in the middle of the array breaks this update?

**Comment by Majrusz** [comment]
Thanks for the report! It turned out that I made some silly mistake and the game could crash when multiple players participated in the Undead Army. Anyway it was fixed here 60c9c7cd182a8110eea3c43cf0703c5182545d4f and today I will prepare 1.7.2 release with that fix included

**Comment by Majrusz** [comment]
1.7.2 version has been released, so I am closing this thread (feel free to reopen this thread if you encounter another crashes)
