### ISSUE TITLE
[1.19.2]NullPointerException: Cannot invoke "Object.getClass()" because "instance" is null

### ISSUE THREAD

**Issue by OcrSu** [Majrusz/MajruszsProgressiveDifficultyMod#132]
Game Crash when creating new world....\
Java17
Win10 x64
[crash-2023-03-10_07.11.16-server.txt](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/10937052/crash-2023-03-10_07.11.16-server.txt)

**Comment by superdude808** [comment]
same crash as above literally not figuratively 
[crash-2023-03-10_17.27.56-server.txt](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/10940666/crash-2023-03-10_17.27.56-server.txt)
[latest.log](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/10940668/latest.log)

**Comment by Majrusz** [comment]
Thanks for the report, 1.7.3 has been released with crash fix included
