### ISSUE TITLE
Mobs starting to spawn in underground like crazy

### ISSUE THREAD

**Issue by alexoshowo** [Majrusz/MajruszsProgressiveDifficultyMod#135]
Mobs spawning in caves in insane amount, and causing a lot of memory leaks and TPS fall on server

**Comment by Majrusz** [comment]
Hi, what version are you using? It was recently fixed https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/issues/125

**Comment by Ladocterus** [comment]
I suspect that I ran into the same issue.
Something with the Group spawning, when spawning zombie miner groups underground.
server keeps spitting out : 
[server thread/WARN] [minecraft/PersistentEntitySectionManager]: UUID of added entity already exists: Zombie['Zombie'/9694, l='ServerLevel [world]'

**Comment by Majrusz** [comment]
It has been fixed in recent 1.7.4 release
