### ISSUE TITLE
Crush on village raid start

### ISSUE THREAD

**Issue by laudemort** [Majrusz/MajruszsProgressiveDifficultyMod#137]
Hi
I have problem, running server on arclight everything works ok except villages with raid, when raid starts server crashes.
majruszs-difficulty-1.16.4-1.1.0
majrusz-library-1.16.4-2.0.1.jar

Crush log:
https://pastebin.com/MQt9sUVB

Is there any way to disable village raids?

**Comment by Majrusz** [comment]
Hi, thanks for the report, but I stopped supporting 1.16.X many months ago
