### ISSUE TITLE
[1.18.2-1.7.3] Enderium Shard Ore missing?

### ISSUE THREAD

**Issue by Thombias** [Majrusz/MajruszsProgressiveDifficultyMod#139]
Hi there, so i'm setting up a modpack and noticed that enderium is unobtainable because the ore appears to be missing, although the worldgen place_feature & configured_feature are still in the mod's data folder?
Is this an incompatibility with some other mod that somehow removed the ore or is this an oversight?
I flew through the end with the enderium shard locator and was unable to find anything. I have no mods installed that fundamentally change the world generation of the end, only some new features that get placed on top of the vanilla end.

Here some screenshots with JEI being unable to find the ore (i also looked into the creative tab, but it isn't there) and a mod list down below:
![2023-05-01_22 39 44](https://user-images.githubusercontent.com/46842890/235528286-46dfe2d3-d41a-4b59-a9f7-c9516aeb2bc7.png)
![2023-05-01_22 39 32](https://user-images.githubusercontent.com/46842890/235528290-d95f0c4e-58d9-4e24-bf39-5904086666c0.png)
![Mod list](https://user-images.githubusercontent.com/46842890/235528299-0193f057-1627-4701-b84d-f0b5391da2ff.PNG)

**Comment by Majrusz** [comment]
Thanks for the report, it has been fixed in recent 1.7.4 release. (it is both obtainable via creative menu and in the End)
![image](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/assets/57394914/485e585f-1db0-4642-b5c8-cf3d7b354752)
