### ISSUE TITLE
Client Singleplayer Crash When moving around in creative

### ISSUE THREAD

**Issue by celsiusqc** [Majrusz/MajruszsProgressiveDifficultyMod#14]
https://pastebin.com/fY4SkZ7h

**Comment by celsiusqc** [comment]
1.16.4
35.1.37 (forge)
0.3.1 (Majruszs Diff.)

**Comment by Majrusz** [comment]
Actually I have fixed this few hours ago, check out the latest version 0.3.2!  :)
