### ISSUE TITLE
Problem with Better Combat & AlexsMobs

### ISSUE THREAD

**Issue by Explode007** [Majrusz/MajruszsProgressiveDifficultyMod#140]
Forge 43.2.6 - 1.19.2
Majrusz Lib - 3.3.0
Majrusz Difficulty - 1.7.3

Problem: When swinging at mobs that have strong collision (meaning the sorta act like boats do in minecraft with their collision) with both Majrusz difficulty and better combat involved, the game freezes up and is in an eternal state of lag until you close the game itself.

Things like the Giant squid and cachalot whale have this 'strong collisionbox'

https://github.com/ZsoltMolnarrr/BetterCombat/issues/243#issue-1683584823

**Comment by Majrusz** [comment]
Hi, thanks for the report. There was a bug in my library that caused that and it will be fixed in upcoming 4.1.0 release https://github.com/Majrusz/MajruszLibrary/pull/18/commits/02fef02b6852da032ecdc11e92db0d8136f1848f (I will close this thread once it is released)
