### ISSUE TITLE
Crash with Enhanced Celestials - Blood, Blue, & Harvest (Super) Moons ?

### ISSUE THREAD

**Issue by Thysium** [Majrusz/MajruszsProgressiveDifficultyMod#141]
Hello, is this a compatibility problem?

https://pastebin.com/KBHedTMY

**Comment by Majrusz** [comment]
Hi, thanks for the report. It is a duplicate of https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/issues/142 so I will close this one
