### ISSUE TITLE
[1.19.2-1.7.3] Cannot invoke "net.minecraft.resources.ResourceLocation.equals(Object)" because "id" is null

### ISSUE THREAD

**Issue by HowardDaFlamingo** [Majrusz/MajruszsProgressiveDifficultyMod#142]
The game crashes as soon as the "tank" boss spawns inside of undead raid. It doesn't continuously crash after it does spawn and only crashes when it spawns via the raid.
[crash-2023-05-06_18.24.17-server.txt](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/11413491/crash-2023-05-06_18.24.17-server.txt)

**Comment by HowardDaFlamingo** [comment]
turns out its any boss mob that spawns in the raid

**Comment by Majrusz** [comment]
Hi, thanks for the report. It has been fixed 05ef4a12d9f1c8d4730ec110a37a90392c381840 and soon I will release a 1.7.5 version with that fix included
