### ISSUE TITLE
End shard locator not dropping

### ISSUE THREAD

**Issue by clytemnestra** [Majrusz/MajruszsProgressiveDifficultyMod#143]
Hello, am playing roguelike adventures 2 v1.3 and killed ender dragon over 30 times and no end shard locator in the bags so far. Is it really that low drop chance, is it bugged or am I super unlucky?

**Comment by Majrusz** [comment]
Hi, there was a bug and most of the time you did not get the whole loot. It was fixed in the recent update for 1.18.2 and 1.19.2, but 1.16.5 was not supported for a while now, so sorry but I do not plan to fix it at the moment
