### ISSUE TITLE
forge server (1.19.2) undead army wave crash

### ISSUE THREAD

**Issue by uchikun** [Majrusz/MajruszsProgressiveDifficultyMod#144]
[latest.log](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/11607274/latest.log)
not sure what is causing the crash :(

**Comment by Majrusz** [comment]
Hi, thanks for the report, but it is a duplicate of https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/issues/142
