### ISSUE TITLE
Server Side Crash

### ISSUE THREAD

**Issue by NotCaptainPyro** [Majrusz/MajruszsProgressiveDifficultyMod#147]
[crash-2023-06-03_13.33.45-fml.txt](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/11642886/crash-2023-06-03_13.33.45-fml.txt)

crash on server side with new update

**Comment by Majrusz** [comment]
Hi, thanks for the report is has been fixed in my library mod, and soon 4.2.0 will be available
