### ISSUE TITLE
Cursed armor can drown

### ISSUE THREAD

**Issue by Aceplante** [Majrusz/MajruszsProgressiveDifficultyMod#149]
I understand it sinking like a skeleton, but it also drowns which doesn't make sense.

forge 1.18.2

**Comment by Majrusz** [comment]
Hi, thanks for the report. Yeah, it makes no sense, I will fix it soon

**Comment by Majrusz** [comment]
Okay, it has been fixed here f24ad8b2ee26755faea8f53b71c5c6af68324b70. Within next few days I will release a new version and close this thread. Once again, thanks for the report
