### ISSUE TITLE
Illusioners spawned in master mode are added to pillager raids

### ISSUE THREAD

**Issue by Smokedeuch** [Majrusz/MajruszsProgressiveDifficultyMod#15]

**Comment by Majrusz** [comment]
Is this a bug or an idea?

**Comment by Smokedeuch** [comment]
Bug,Sorry

**Comment by Majrusz** [comment]
They may spawn naturally not far from the raid and thus join it. I don't plan to change it, It was not intentional, but I think the effect is pretty cool.

**Comment by Smokedeuch** [comment]
Yeah but they can spawn underground creating a stupid game of needle in the haystack especially with mods like YUNG's Better Caves.At least a config option would be nice.

**Comment by Majrusz** [comment]
Sorry I didn't fully understand the problem then. This will be fixed in the next update.
