### ISSUE TITLE
Enderium Ore not appearing in version 1.18.2-1.7.7

### ISSUE THREAD

**Issue by Wolfrest** [Majrusz/MajruszsProgressiveDifficultyMod#153]
![Captura de pantalla 2023-06-28 195452](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/assets/138082261/4bf3e19d-98ff-46a2-80ed-d98d2c2de761)
![Captura de pantalla 2023-06-28 195447](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/assets/138082261/c189b449-adec-49a8-b1c7-61d46c4bcfe1)

**Comment by Majrusz** [comment]
Hi again, 1.8.0 has been released and it should not be an issue anymore
