### ISSUE TITLE
Cursed armor crashes my server

### ISSUE THREAD

**Issue by Fells2** [Majrusz/MajruszsProgressiveDifficultyMod#157]
I use Exaroton servers, it crashes when I a chest is open, it appears and sometimes (most of the time) crashes the game. This is my crash log https://mclo.gs/MVOX2gr and this is all mods I have.
![image](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/assets/91272398/2c7cd3c1-e227-468a-b9cb-158bd5b2a06f)
![image](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/assets/91272398/6e671bbc-8d7f-421a-809a-a3c5526c9a74)
![image](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/assets/91272398/3adfbb95-0a55-4b8e-bcdc-dd5dad3fad25)
![image](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/assets/91272398/97b9da89-3823-45fd-9b7b-e0ebfa13a213)

**Comment by Majrusz** [comment]
Hi, thanks for the report. It looks like Alternacraft is responsible for that crash https://www.curseforge.com/minecraft/mc-mods/alternacraft
