### ISSUE TITLE
Config to turn off Skykeeper structure?

### ISSUE THREAD

**Issue by iamSleepl3ss** [Majrusz/MajruszsProgressiveDifficultyMod#16]
Heya! 
I love the mod, but I was wondering if there is a config to turn off the giant Skykeeper structure? 
It's very well built, but it just ruins the "immersion" or general view when watching large landscapes.

If there is none, and/or if there is no config setting to turn the generation of these structures off, could you please consider this for the next update? ( or a quick hotfix? ;)  )

**Comment by Majrusz** [comment]
Hello, I have added config for disabling this structure. It will be available in the next update 0.4.0.
