### ISSUE TITLE
Spawn Blocker - Not working for most mobs (v1.7.7)

### ISSUE THREAD

**Issue by Cixon** [Majrusz/MajruszsProgressiveDifficultyMod#160]
Using 1.18.2 Minecraft
Single player environment.

Here's Config:
[majruszsdifficulty-server.txt](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/12157297/majruszsdifficulty-server.txt)

MOB by Mod:

Ghost - Ice and Fire mod.
problem: ghosts still spawn from graveyard soil at night and trapped ghost chests.

Spawnerhead - [Spawnerhead](https://www.curseforge.com/minecraft/mc-mods/spawner-head) mod.
problem: still randomly spawns at night.

**Comment by Cixon** [comment]
Normal Mode should prevent these entities from spawning until player goes to the Nether.
According to my configuration set in the .txt document.

**Comment by Majrusz** [comment]
Thanks for the report, I fixed that here 6b6525ad91364e8e84ed2707cf0b41c2bf44c4b1 and soon will release a new mod version with that fix included

**Comment by Majrusz** [comment]
Hi again, 1.8.0 has been released and it should not be an issue anymore
