### ISSUE TITLE
[Request]: Datapack tags or even json file list to define tools which don't bleed.

### ISSUE THREAD

**Issue by Darkmega18** [Majrusz/MajruszsProgressiveDifficultyMod#161]
Would it be possible to get a capability to tag items that shouldn't bleed?
or alternatively a json list that can set the actual "base" percentage chance of being inflicted bleed, but also optionally, any status effect.

For example, it could be a chance to apply poison for certain unique weapons. or someone might want a chance to inflict some kind of armor break effect or stun from some of the various mods on maces and blunt weapons instead of bleed.

Default should be the bleed, but there should be the option to not bleed at the very least... cause I highly doubt whacking someone with an ex nihilo crook or trying to bap them over the head with a spoon should cause bleed.
![image](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/assets/8104689/d11f69a9-985d-40ba-95ad-47a9ef5e1c51)

**Comment by Majrusz** [comment]
Hi, thanks for the report, and I added json file support for Bleeding recently but it was not published yet. The structure will look as following:
```
[
  {
    "id": "minecraft:trident",
    "chance": 0.25
  },
  {
    "id": "{regex}.*_sword",
    "chance": 0.25,
    "enchantments": [
      {
        "id": "minecraft:sharpness",
        "extra_chance": 0.015
      },
      {
        "id": "{regex}(minecraft:smite)|(minecraft:bane_of_arthropods)|(majruszsenchantments:misanthropy)",
        "extra_chance": 0.01
      }
    ]
  },
  {
    "id": "{regex}.*_axe",
    "chance": 0.225,
    "enchantments": [
      {
        "id": "minecraft:sharpness",
        "extra_chance": 0.015
      },
      {
        "id": "{regex}(minecraft:smite)|(minecraft:bane_of_arthropods)|(majruszsenchantments:misanthropy)",
        "extra_chance": 0.01
      }
    ]
  },
  {
    "id": "{regex}(.*_pickaxe)|minecraft:shears",
    "chance": 0.2
  },
  {
    "id": "{regex}.*_shovel",
    "chance": 0.175
  },
  {
    "id": "{regex}.*_hoe",
    "chance": 0.15
  }
]
```
This feature will make you able to customize what inflicts Bleeding and will not include spoons by default, however I do not plan to add custom effects to this structure at the moment. Anyway I hope to release updated mod soon

**Comment by Darkmega18** [comment]
oh I see. Seems good. thanks for letting me know. :o

**Comment by Majrusz** [comment]
Hi again, 1.8.0 has been released and you are now able to modify Bleeding chance per item

**Comment by Darkmega18** [comment]
eeeexcellent.
I'll fiddle with it eventually then. :D
