### ISSUE TITLE
[Request] make soul jar compatible with curios mod

### ISSUE THREAD

**Issue by brandonmaster590** [Majrusz/MajruszsProgressiveDifficultyMod#162]
Have soul jar able to be put in a curios slot.

**Comment by gusbaruc** [comment]
I totally agree!

**Comment by Darkmega18** [comment]
Yes please! Same slot as your other little trinkets perhaps. Or a dedicated slot for one at a time.

**Comment by Majrusz** [comment]
Hello, I decided that it would be quite strong when combined with shield, so I will not add curios compatibility but with the latest 1.9.0 release it is now possible to apply weaker variants of bonuses to any kind of shield. Thanks for the suggestion though!

**Comment by Darkmega18** [comment]
Can this be extended to a tag? perhaps people can decide and tag items as "canusesouljar" and those items can have one imbedded in them? Could be useful.
