### ISSUE TITLE
Shields can't stop Bleeding

### ISSUE THREAD

**Issue by Dr-WeiAL** [Majrusz/MajruszsProgressiveDifficultyMod#163]
In my testing, I found that skeleton shots at players holding up shields still cause the Bleeding effect
Minecraft version: 1.20.1 Forge
Mod version: 1.7.7

**Comment by Majrusz** [comment]
Thanks for the report, I fixed that 332a5719c8fbe2ac05d7dad36391e63b1a3e2965 and soon I will release new mod version

**Comment by Majrusz** [comment]
Hi again, 1.8.0 has been released and it should not be an issue anymore

**Comment by Dr-WeiAL** [comment]
It's fixed.
But can you please make it compatible with [Shield mechanics](https://www.curseforge.com/minecraft/mc-mods/shield-mechanics)? It still bleeds when installing [Shield mechanics](https://www.curseforge.com/minecraft/mc-mods/shield-mechanics).
