### ISSUE TITLE
Option to add new game stages

### ISSUE THREAD

**Issue by samjviana** [Majrusz/MajruszsProgressiveDifficultyMod#164]
Currently the mod has "Normal", "Expert" and "Master" right?
Is it possible to add a forth one? to increase the difficulty even more?
I mean ... I could just adjust the current modes, but adding more difficulty modes would be nicer.

**Comment by Majrusz** [comment]
Hi, it is not possible at the moment, but I will consider such option

**Comment by Majrusz** [comment]
Hello, thanks for the suggestion, I added such option in the latest 1.9.0 release
