### ISSUE TITLE
Remove baked in bleed immunity please

### ISSUE THREAD

**Issue by zekeflynn** [Majrusz/MajruszsProgressiveDifficultyMod#167]
Remove baked in bleed immunity please / Allow to bleed more types of mobs

Hi!

"(all undead mobs are immune by default)."

Could you... remove this? Just add undead ID's to the config default list like with the horse?

I also noticed bleed doesn't work on any other modded mobs.

The bleed chance per tool was amazing to flesh out this mechanic but being useless on 90% of mobs sets it back.

**Comment by Majrusz** [comment]
Hello, thanks for the suggestion, I removed that from config and now you have more control what type of mobs can bleed in the latest 1.9.0 release
