### ISSUE TITLE
Soul Jar attack speed bonus not applying 1.19.2 forge

### ISSUE THREAD

**Issue by bomasborber** [Majrusz/MajruszsProgressiveDifficultyMod#169]
Was rewarded a "Endermen, Sniffer, Dolphin" Soul Jar; the bonus reach and bonus swim speed are working fine, but the attack speed one has been inconsistent, 90% of the time not giving the bonus.
![image](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/assets/53311323/537c4d84-e05e-4cc1-b79b-ccb5f5bb99db)

**Comment by Majrusz** [comment]
Thanks for the report, I have fixed it here abc05e7524a2fc84c251ae6bed0c6718c5c213b8 and when I release updated mod I will close this thread
