### ISSUE TITLE
Zombified Piglin Groups in the nether spawn zombies instead of zombified piglins

### ISSUE THREAD

**Issue by NJL5390** [Majrusz/MajruszsProgressiveDifficultyMod#17]
Progressive difficulty version: 0.3.2
Forge version: 36.0.1
Minecraft Version: 1.16.5

Hello!

I've noticed when testing out this mod and finding mob "groups" in the nether, that zombified piglin groups spawn as zombies instead of zombified piglins.
![2021-01-21_16 43 27](https://user-images.githubusercontent.com/64381954/105387585-9b041b80-5c0d-11eb-8e60-f90b88e754b5.png)
In this case the leader (who has leather armour) has spawned as a zombified piglin as normal but the rest of his group spawned as zombies, I've noticed this happen quite frequently in the latest version of the mod and always happens whenever a zombified piglin spawns with a group.

**Comment by Majrusz** [comment]
Thanks for reporting that! It will be fixed in the next update 0.4.0.

**Comment by Majrusz** [comment]
I have fixed this already, in the next update it will work properly.
