### ISSUE TITLE
Double drop

### ISSUE THREAD

**Issue by TsuneZebra** [Majrusz/MajruszsProgressiveDifficultyMod#171]
How do I disable the double drop of monster gear in Expert and Master difficulty？

**Comment by Majrusz** [comment]
Hello, inside your world config folder you can find `majruszsdifficulty-server.toml` and there is Features.DoubleLoot to do that

**Comment by TsuneZebra** [comment]
I can't find the majruszsdifficulty-server.toml in my world config folder,only majruszs-difficulty-common.toml in config.version 1.16.4-1.1.0
