### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Inf0214** [Majrusz/MajruszsProgressiveDifficultyMod#172]
I have a crash when starting the game. 
Error: java.lang.NullPointerException: Registry Object not present: majruszsdifficulty:evoker_fang_scroll
Its quite a large modpack... ~300 mods
Minecraft: 1.18.2
Forge: 40.2.10
MajruszsProgressiveDifficulty: 1.18.2-1.8.0
Here are my logs: 
[debug.log](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/12570110/debug.log)
[latest.log](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/12570112/latest.log)
[crash-2023-09-10_21.52.11-client.txt](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/12570144/crash-2023-09-10_21.52.11-client.txt)

Tell me if I can help in any way

**Comment by Majrusz** [comment]
Hello, thanks for the report, I have fixed here a1db154f7759c248c01461dcbdd01716bbcbf991 and I will soon release a new mod version
