### ISSUE TITLE
Unkillable mobs?

### ISSUE THREAD

**Issue by zekeflynn** [Majrusz/MajruszsProgressiveDifficultyMod#173]
My players reported running into undead mobs both alone in the overworld, in zombie farms, and in undead raids that simply do not die. They sit at 1 hp / half a heart and make a weird bling sound when hit. Could not for the life of me find out why and started removing mods one by one. Removed MajDifficulty and the mob was killable again. Seems intentional due to the bling sound the mob does when hit at 1 hp. However, cannot find any explanation for this. Players were very frustrated.

**Comment by Majrusz** [comment]
Hello, can you send me a debug log?

**Comment by zekeflynn** [comment]
[debug.log](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/12620784/debug.log)
[screen-recorder-fri-sep-15-2023-12-00-28.webm](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/assets/33818126/6c9e4612-c210-46c9-ac21-62ecf37067fd)

**Comment by Majrusz** [comment]
Unfortunately I do not see anything in the debug log. This file contains only information from the last session, have you hit any of unkillable mobs in that session? If not, can you hit one of them and send me a new debug log?

**Comment by zekeflynn** [comment]
Hitting mobs - any mobs unkillable or not - doesn't show on my debug log. Fresh one looks like this:

> [16Sep2023 07:10:46.058] [Render thread/DEBUG] [Diet/]: Loaded com.illusivesoulworks.diet.platform.services.ForgeClientService@273c0dcc for service interface com.illusivesoulworks.diet.platform.services.IClientService
[16Sep2023 07:10:46.183] [Render thread/DEBUG] [mixin/]: Mixing OrderedTextToolTipAccessor from vinery-common.mixins.json into net.minecraft.client.gui.screens.inventory.tooltip.ClientTextTooltip
[16Sep2023 07:15:29.256] [Render thread/INFO] [xaero.map.WorldMap/]: Finalizing world map session...

between 7:10 and 7:15 is when I hit both the unkillable skelly from the video as well as a bunch of piglins running around. Gave a couple minutes between that and exiting to make sure.
