### ISSUE TITLE
Expert Mode not triggering.

### ISSUE THREAD

**Issue by AdrianTheGeek** [Majrusz/MajruszsProgressiveDifficultyMod#175]
Expert mode isn't triggering, in the expert config in "triggering dimensions" all that it says is "{regex}.*}". How do I add nether and other modded dimensions there?

**Comment by AdrianTheGeek** [comment]
I am also using Incendium wich changes the nether alot if that helps.

**Comment by Majrusz** [comment]
Hello, thanks for the report, there was a bug in my library mod that I fixed recently, check out the latest 5.1.1 version

**Comment by AdrianTheGeek** [comment]
Alright. Thanks!
