### ISSUE TITLE
[1.19.2] Difficulty stage automatically changes to expert when going into other dimensions even if not configured to do so.

### ISSUE THREAD

**Issue by Darkmega18** [Majrusz/MajruszsProgressiveDifficultyMod#177]
majruszs-difficulty-1.19.2-1.8.1.jar

When I got onto my server today, I went into my tent and realized the majrusz difficulty config had reset on me because the game switched to expert mode.
I edited the config and reloaded, making sure that the setting was for expert mode to only actually activate when going into the nether. however still continued switching.

I also couldn't find the setting you used to have which let me turn off the effect of having any dimension trigger expert mode. Did it get removed? Because now I can't properly configure my modpack again. You did this to me in my last modpack too... please fix. :V

**Comment by Majrusz** [comment]
Hello, thanks for the report, there was a bug in my library mod. Check out the latest 5.1.2 library version, it should fix your issue (if not feel free to reopen this thread)

**Comment by Darkmega18** [comment]
Roger-roger. Thanks, Maj.
