### ISSUE TITLE
1.20.1 Crash

### ISSUE THREAD

**Issue by AMRH2000** [Majrusz/MajruszsProgressiveDifficultyMod#178]
When I kill mobs in Undead Army, the game crashes
1.20.1
forge 47.1.3
majruszs-difficulty-1.20.1-1.8.1
majrusz-library-1.20.1-5.1.1
[crash-2023-09-22_03.28.23-server.txt](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/12694332/crash-2023-09-22_03.28.23-server.txt)

**Comment by Majrusz** [comment]
Hello, thanks for the report, I fixed it with the latest 1.9.0 release
