### ISSUE TITLE
How to add Dimensions to Difficulty Increase?

### ISSUE THREAD

**Issue by guitarist4hire** [Majrusz/MajruszsProgressiveDifficultyMod#179]
it's my understanding that going in to the nether updates the game state to expert mode. i'm not seeing anything to indicate that this change has taken place, and im not sure how to do so?

also, i'd like for the same effect to take place when entering the twilight forest dimension from the aforementioned mod.

any help with these issues would be greatly appreciated!

Thank y0u, and have a wonderful day!

**Comment by Majrusz** [comment]
Hello, sorry for the late response, but there used to be a bug that caused that, the latest version of difficulty mod should work fine
