### ISSUE TITLE
Elite Skeletons spawn too frequently in certain nether biomes

### ISSUE THREAD

**Issue by NJL5390** [Majrusz/MajruszsProgressiveDifficultyMod#18]
Progressive difficulty: 0.3.2
Forge: 36.0.1
Minecraft: 1.16.5

Hello,
When I've been exploring the nether, I've noticed that certain nether biomes such as Crimson forests and Warped forests, seem to spawn elite skeletons way too frequently, which often leads to these skeletons crowding out other mobs which should be spawning more frequently.
![2021-01-21_17 42 21](https://user-images.githubusercontent.com/64381954/105391423-094add00-5c12-11eb-8918-f7fb12a653b0.png)
This is especially true with modded nether biomes such as the ones from biomes o plenty:
![2021-01-21_17 43 44](https://user-images.githubusercontent.com/64381954/105391556-2384bb00-5c12-11eb-91aa-b69286597c37.png)

I feel like these elite skeletons should be limited to only being able to spawn where regular skeletons appear, such as soul sand valleys and nether fortresses and not in places such as crimson forests or warped forests where they could crowd out other mobs and make them much rarer.

Their spawn rate in the overworld is fine though.

Alternatively, A config option could be added to determine which nether biomes these elite skeletons can spawn in.

**Comment by Majrusz** [comment]
Thanks, I will limit the spawning of Elite Skeletons only to biomes where Skeletons/Wither Skeletons spawn in the next update.

**Comment by Majrusz** [comment]
I've changed the way skeletons spawn, this will be noticeable in the next version.
