### ISSUE TITLE
[Suggestion] Custom Mob Groups

### ISSUE THREAD

**Issue by NiveStinks** [Majrusz/MajruszsProgressiveDifficultyMod#180]
I realize it'd probably be a lot of work, but the Mob Groups mechanic is really interesting and would be a very versatile tool in the hands of modpack developers. There's boundless amounts of modded mobs that could fit right in, and there's even a lot of wacky potential just with vanilla mobs. Groups of Wither Skeletons in the Nether, groups of Drowned in the seas, a Spider Jockey leading Spiders, etc.

**Comment by Majrusz** [comment]
Hello, thanks for the suggestion, I added it in 1.9.0 release
