### ISSUE TITLE
Crash when lightning struck zombie horse

### ISSUE THREAD

**Issue by Rimplestilt** [Majrusz/MajruszsProgressiveDifficultyMod#181]
Server crashed right as lightning struck a zombie horse. Was fine after restarting the server. The zombies on horses has spawned successfully.

[crash-2023-10-21_22.44.08-server.txt](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/13063934/crash-2023-10-21_22.44.08-server.txt)

**Comment by Majrusz** [comment]
Hello, it should be fixed with the latest mod version
