### ISSUE TITLE
Rain-rain-rain, gameplay = rain

### ISSUE THREAD

**Issue by DonorKrovi** [Majrusz/MajruszsProgressiveDifficultyMod#182]
Make it possible to turn off the rain after spawning an army of the undead, the entire gameplay on the server turns into an eternal downpour, which is just terrible!

**Comment by Majrusz** [comment]
Hello, thanks for the report, as it turned out there was a bug in changing the weather and that is why it was raining all the time. It should be fixed in the latest release
