### ISSUE TITLE
Library 6.0.0 not permitted

### ISSUE THREAD

**Issue by Jackiecrazy** [Majrusz/MajruszsProgressiveDifficultyMod#183]
I don't know if this is a bug, but by the mods.toml specs, mLib 6.0.0 is excluded, which means this mod cannot be used alongside the updated accessories mod. The same applies for Majrusz's Enchantments.

**Comment by Lucksinia** [comment]
Will also add that only libraries 5.1.x are allowed, and considering that all other compatible mods are already using libraries from 6.0.0 to 7.0.0 (as per error message)

**Comment by Majrusz** [comment]
Hello, I fixed it with the latest 1.9.0 release
