### ISSUE TITLE
[Suggestion] You can determine the bleeding immunity factor based on the armor value!

### ISSUE THREAD

**Issue by Qee1y** [Majrusz/MajruszsProgressiveDifficultyMod#184]

**Comment by Majrusz** [comment]
Hello, great idea, I will add it with the next 1.9.0 version

**Comment by Majrusz** [comment]
Hello, thanks for the suggestion, I implemented it in the latest 1.9.0 release and you can read about it here https://majruszs-progressive-difficulty.fandom.com/wiki/Bleeding
