### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by d-rick** [Majrusz/MajruszsProgressiveDifficultyMod#186]
NO INICIA EL JUEGO LUEGO DE ACTUALIZAR
[crash-2023-12-02_18.04.20-client.txt](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/13537591/crash-2023-12-02_18.04.20-client.txt)

[latest.log](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/13537594/latest.log)

**Comment by Majrusz** [comment]
Hello, thanks for the report, it should be fixed with 1.9.2 release
