### ISSUE TITLE
Incompatible with Marium's Soulslike Weaponry (Fabric 1.20.1)

### ISSUE THREAD

**Issue by Whisp-0** [Majrusz/MajruszsProgressiveDifficultyMod#187]
Crashing on world creation. Only two mods + necessary libraries are installed
[latest.log](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/13538859/latest.log)

**Comment by Majrusz** [comment]
Hello, thanks for the report, I fixed it with the latest 7.0.1 library release
