### ISSUE TITLE
[1.20.X] Crash -  java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by NanoAi** [Majrusz/MajruszsProgressiveDifficultyMod#189]
After adding Progressive Difficulty I can't seem to launch the game at all. In console I get an error about a missing class.

Version: majruszs-difficulty-neoforge-1.20.1-1.9.1.jar

Crash Log: 
[a-crashlog-1.txt](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/13539854/a-crashlog-1.txt)

**Comment by Majrusz** [comment]
Hello, thanks for the report, I fixed with the latest 1.9.2 release

**Comment by NanoAi** [comment]
> Hello, thanks for the report, I fixed with the latest 1.9.2 release

Within 12 hours too; error fixing speedrun Majrusz edition.

Thanks!
