### ISSUE TITLE
Error 1

### ISSUE THREAD

**Issue by ceifadorcinixtru** [Majrusz/MajruszsProgressiveDifficultyMod#192]
When i try to launch the game with the last version(1.9.2) in 1.20.1 minecraft, the game crashes.

Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [majruszsdifficulty-common.mixins.json:IMixinCreeper from mod majruszsdifficulty] from phase [DEFAULT] in config [majruszsdifficulty-common.mixins.json] FAILED during APPLY
[Info: 2023-12-04 22:57:41.1652538: MinecraftJavaLoggingContext.cpp(65)] Game/game () Info at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)

[launcher_log.txt](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/13552304/launcher_log.txt)

**Comment by Majrusz** [comment]
Hello, thanks for the report, as it turned forge version have not built properly, but you can now download the same version without such problems
