### ISSUE TITLE
[NeoForge][1.20.1] Mixin apply failed majruszsdifficulty-common.mixins.json:IMixinCreeper -> net.minecraft.world.entity.monster.Creeper

### ISSUE THREAD

**Issue by NanoAi** [Majrusz/MajruszsProgressiveDifficultyMod#193]
The game starts launching normally but sometime during the launch process just closes with the mixin error provided.

Please note I tried running `majruszs-difficulty-forge-1.20.1-1.9.2.jar` on NeoForge 1.20.1 as the code base is compatible... and the game ran fine. I was even able to boot up and play a Singleplayer world with no issues.

Personally, I think this could be some compatibility issue with another mod.

<details>
Also hit me up on Discord. ^^
</details>

- Version: majruszs-difficulty-neoforge-1.20.1-1.9.2.jar
- Game Version: 1.20.1 on NeoForge.

[another_error_for_you.txt](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/13594497/another_error_for_you.txt)

**Comment by Majrusz** [comment]
Hello, thanks for the report, the latest 1.9.3 version should work fine
