### ISSUE TITLE
Can't go into creative or inventory

### ISSUE THREAD

**Issue by ReboundRefice** [Majrusz/MajruszsProgressiveDifficultyMod#197]
[crash-2023-12-09_15.26.29-client.txt](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/13625924/crash-2023-12-09_15.26.29-client.txt)
At first I thought it was another mod so I kept disabling it but it keeps popping up saying its this. Wasnt sure how to fix

**Comment by Majrusz** [comment]
Hello, try to remove `majruszsdifficulty.json` in your configuration file and let it regenerate once again, looks like the values are invalid
