### ISSUE TITLE
Treasure Bags from fishing and from undead army cannot be disabled

### ISSUE THREAD

**Issue by AeiouEnigma** [Majrusz/MajruszsProgressiveDifficultyMod#20]
Almost every feature in this mod is now configurable as of the latest update. Treasure Bags are a notable exception.

**Comment by Majrusz** [comment]
You are right, I will add an option to disable them.

**Comment by Nider001** [comment]
I believe the same should be applied to bandages if possible, there is no need for them if you disable the bleeding effect itself

**Comment by Majrusz** [comment]
It took me a while, but I finally added it. In the next update there will be an option to disable treasure bags! Unfortunately it will not be possible to disable bandages.
