### ISSUE TITLE
Startup crashes after add OptiFine

### ISSUE THREAD

**Issue by Fiocher** [Majrusz/MajruszsProgressiveDifficultyMod#200]
Game Version: 1.20.1
Forge Version: 47.2.18
OptiFine Version: 1.20.1 HD U I6
Only Majrusz's Progressive Difficulty and Majrusz Library were added, without other mods.
Startup normally after delete OptiFine.
[crash-2023-12-22_23.37.48-client.txt](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/13754009/crash-2023-12-22_23.37.48-client.txt)

**Comment by Majrusz** [comment]
Hello, thanks for the report, I fixed it with the latest 1.9.6 release
