### ISSUE TITLE
[1.20.1] Fabric - Incomaptibility with Tinkerer's Smithing

### ISSUE THREAD

**Issue by FLSoz** [Majrusz/MajruszsProgressiveDifficultyMod#205]
Fabric 1.20.1

![image](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/assets/65517812/af81304a-d4b5-48fc-b25b-a593585c45ca)
sample log: https://mclo.gs/GllhrFf

It's crashing here: https://github.com/sisby-folk/tinkerers-smithing/blob/46db139f9236992501f8b763a42f301f95448e33/src/main/java/folk/sisby/tinkerers_smithing/TinkerersSmithingLoader.java#L282

Likely because of this: https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/blob/544a629793cfb2fb7e18107408259646aad48603/common/src/main/java/com/majruszsdifficulty/items/CustomArmorMaterial.java#L96

Why is `getName` set to client only?

**Comment by Majrusz** [comment]
Hello, thanks for the report. It seems like this `@OnlyIn` annotation is a leftover from older minecraft versions and it is not required anymore, I have fixed it here 00e7c35438d5c1118ec42a4712a759494cf38567 and will include this fix with the next 1.9.7 release
