### ISSUE TITLE
[1.20.1] Crashes occuring while inside dungeon relating to Cursed Armor spawn

### ISSUE THREAD

**Issue by GenericCherrySwitch** [Majrusz/MajruszsProgressiveDifficultyMod#208]
The game crashed while I was clearing mobs inside a dungeon, the crash report apparently mentions something about failing to find the position to spawn the Cursed Armor mob.

The relevant crash report is attached below:
https://gist.github.com/GenericCherrySwitch/1dbdcbe43c1c2f33c9e9428a1f5ca27f

**Comment by Majrusz** [comment]
Hello, thanks for the report, I fixed it with the latest 1.9.7 release
