### ISSUE TITLE
[1.20.1] Shift + Right clicking lootbag when highlighted kicks me out of the game

### ISSUE THREAD

**Issue by GenericCherrySwitch** [Majrusz/MajruszsProgressiveDifficultyMod#209]
As described in the title: 
If you hold Shift then Right click when you are highlighting a lootbag in your inventory*, the game will kick you out of the game due to some thread-related issue while Concurrent Chunk Management Engine is loaded in the game.

The relevant log entry is linked here: https://gist.github.com/GenericCherrySwitch/0bffc30c175debe438a80eff9f552c32

**Comment by Majrusz** [comment]
Hello, thanks for the report, I fixed it with the latest 1.9.8 release
