### ISSUE TITLE
[1.20.1 Fabric/Forge] Undead Army waves don't end with RpgZ installed.

### ISSUE THREAD

**Issue by Sazuzaki** [Majrusz/MajruszsProgressiveDifficultyMod#211]
Hello,

I'm just reporting a small incompatibility with the mod RpgZ, which makes mobs stay as corpses and disappear once looted. It would like to use it in tandem with Progressive Difficulty, but it seems that the Undead Army still detects them as alive if the corpses remain (can be checked with the highlight command), so it results in the wave not ending unless you loot all the corpses. Hopefully this becomes compatible someday, but I'll be removing RpgZ for now.

https://www.curseforge.com/minecraft/mc-mods/rpgz

**Comment by Majrusz** [comment]
Hello, thanks for the suggestion, I have added such compatibility f418e9ad35707dad783bb46d8a12ba0774aae53a and will release it with the next mod version

**Comment by Sazuzaki** [comment]
Sounds good, thanks for the hard work boss
