### ISSUE TITLE
way to disable world gen?

### ISSUE THREAD

**Issue by PabloDnSS** [Majrusz/MajruszsProgressiveDifficultyMod#215]
awesome mod any way to disable world gen and get rif of enderium and end stone as well?

**Comment by Majrusz** [comment]
Hello, at the moment it is not possible unfortunately

**Comment by Majrusz** [comment]
Duplicate of https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/issues/112

**Comment by wilsoffer** [comment]
Use the BlockSwap mod to remove world generation. There are numerous tutorials online
