### ISSUE TITLE
Spawners float in air from undead army event

### ISSUE THREAD

**Issue by D-Bigboy-302** [Majrusz/MajruszsProgressiveDifficultyMod#22]
Playing on my server, when an undead army event happens mob spawners are placed in the air. Typically where the player started the event. The spawners don't disappear after the event as well. It also appears that during an undead event where the spawner is, is where the army runs to.
![2021-01-23_10 30 14](https://user-images.githubusercontent.com/61896885/105609718-ffcf8b00-5d5f-11eb-9b01-dcf19bb226ba.png)

The server is on 1.16.4. Everyone's client is Forge 35.1.37. Mod version: 0.4.0
If you need any additional info, let me know. Thanks for the mod! Me and my friends are having a lot of fun with it!

**Comment by Majrusz** [comment]
Thanks it has been fixed and will work correctly in the next update.
