### ISSUE TITLE
Seems to be incompatible with Nyf's Spiders

### ISSUE THREAD

**Issue by EthanWatsonGH** [Majrusz/MajruszsProgressiveDifficultyMod#240]
When I have Nyf's Spiders installed with this mod spiders can't climb walls, and they just run into them when trying to come after you even if they're only 1 block high.

**Comment by PancakesBatch** [comment]
Please post your version of Minecraft you are on.
I've isolated the mods in 1.20.1 and did not face this conflict.

**Comment by EthanWatsonGH** [comment]
I was on 1.20.1. I'll look into it again and see if it was something else I didn't notice.
