### ISSUE TITLE
(1.16.5) Difficulty Increase Message Not Appearing

### ISSUE THREAD

**Issue by mcquestion** [Majrusz/MajruszsProgressiveDifficultyMod#25]
If you enter the nether/beat the ender dragon for the first time on one save, exit that save, and then enter the nether/beat the ender dragon for the first time on a different save; the "You have released the ancient spirits"/"Impending doom" message does not appear the second time round. 

This bug only occurs if you *do not* restart Minecraft for this whole process, if you restart Minecraft at any stage in between entering the nether/beating the dragon for the first time and the second it will play the message both times.

The bug *will* also occur though if you load a save where you have already entered the nether/beaten the dragon, exit that save, and then enter the nether/beat the dragon on a different save. Again, only if you don't restart Minecraft in between. 

Tbh I can't see this being an issue for anyone other than speed runners so it's not a massive problem and definitely won't be for me personally, only noticed it while testing for a modpack. :)

**Comment by Majrusz** [comment]
Thanks for reporting that! It was serious issue because game state wasn't changing when loading different worlds. It will be working as it should be in the next update.
