### ISSUE TITLE
Feature Request: Blacklist entities from getting the bleed effect

### ISSUE THREAD

**Issue by AzureMonument** [Majrusz/MajruszsProgressiveDifficultyMod#29]
So I've set up a rather decent (if small) villager trading hall in my single player survival world- there's just one problem. Despite playing on hard mode, the villagers didn't seem to have a 100% chance of converting into a zombie. I'm pretty sure, after some simple tests that this is due to them bleeding out before the zombie kills them. (have not gone into creative to confirm, but I'm pretty sure you can simply name a villager egg so they all are named on spawn, then set zombies loose on them and see the death messages.)

It'd be nice if I was able to blacklist certain entities from having the bleed effect.

**Comment by Majrusz** [comment]
In the next update dying from bleeding will properly cause Villagers to transform to Zombie Villagers if they took damage from Zombies before. And also black list will be available for bleed effect.
