### ISSUE TITLE
Feature Request: Damage based slowness + nausea on fall

### ISSUE THREAD

**Issue by AzureMonument** [Majrusz/MajruszsProgressiveDifficultyMod#30]
So I've got a mod that lets me overenchant various enchantments- and one of them is Feather Falling V, which completely negates fall damage at the cost of damaging the boots. However, when I jump off cliffs I still get the slowness effect despite being perfectly fine otherwise, which is kind of off-putting. Especially since one of the main entrances to my base is a roughly 30 block drop onto stone (has a ladder, but falling is faster and more fun).

It'd be nice if I could configure it to give me the effects based on damage, rather than simple height.

**Comment by Majrusz** [comment]
Thanks for reporting this, in the next update fall damage will apply effects only if player takes some amount of damage.
