### ISSUE TITLE
Elite Skeletons spawning in lit up caves & Mycelium biome (v. 0.4.1 | 1.16.4) (0.5.1)

### ISSUE THREAD

**Issue by Petica98** [Majrusz/MajruszsProgressiveDifficultyMod#31]
I've found this issue when building an underground base, the skeletons keep spawning even when (according to more overlays and f3) the light level is always above 7. This happens in a mycelium biome (where they also spawn against mycelium biome spawn restrictions (pretty sure giants also spawn there) 

https://cdn.discordapp.com/attachments/500452400683941904/814492588132139038/unknown.png

**Comment by Petica98** [comment]
Updated the server to v. 0.5.1 Didnt make a difference

**Comment by Majrusz** [comment]
Thanks, I found what was causing this and in the next update it will be fixed :)

**Comment by Petica98** [comment]
Thanks so much, I'll have a look out!
