### ISSUE TITLE
Datapack error on world loading

### ISSUE THREAD

**Issue by Chofito** [Majrusz/MajruszsProgressiveDifficultyMod#33]
Forge: 36.0.44

I tested with only this mod, worlds load correctly but with my custom modpack always crash on world loading.
Recently BetterEndForge fix the same error, I checked the two mods and didn't find a way to port this fix due to a difference between the method used to register Structures (I'm new in forge and java code).

Modpack Link: https://github.com/Chofito/YAMM

BlameReport gives this crash log

****************** Blame Report 1.9.2 ******************

 A crash is most likely going to happen right after this report!
 It seems flying_end_ship | majruszs_difficulty:flying_end_ship is the cause because it is not added 
 to the FlatGenerationSettings.STRUCTURES map. Please let the mod owner 
 of that structure know about this crash. That way they can add their structure 
 to that map since someone is trying to spawn it in a flat/custom dimension.

**Comment by Majrusz** [comment]
Thanks, in the next update it should work properly :)
