### ISSUE TITLE
Crash on world load.

### ISSUE THREAD

**Issue by CyberNewty** [Majrusz/MajruszsProgressiveDifficultyMod#35]
"""
****************** Blame Report 1.9.2 ******************

 A crash is most likely going to happen right after this report!
 It seems flying_end_ship | majruszs_difficulty:flying_end_ship is the cause because it is not added 
 to the FlatGenerationSettings.STRUCTURES map. Please let the mod owner 
 of that structure know about this crash. That way they can add their structure 
 to that map since someone is trying to spawn it in a flat/custom dimension. 
"""

[21:17:08] [Render thread/ERROR] [minecraft/SaveFormat]: Exception reading C:\Users\nicho\Games\multi-mc-minecraft-launcher\mmc-stable-win32\MultiMC\instances\1.16.5\.minecraft\saves\New World\level.dat
java.lang.NullPointerException: null

**Comment by Majrusz** [comment]
Thanks for reporting this bug, it will be fixed in the next update.
