### ISSUE TITLE
[Feature Request] "Bleeding" effect should have custom particle effects for all mobs and not just players

### ISSUE THREAD

**Issue by Neko2n** [Majrusz/MajruszsProgressiveDifficultyMod#36]
I've noticed the bleeding effect drops blood particles all over the place when applied to a player. This is a really nice effect and doesn't get in the way very much in comparison to vanilla potion particles.

There are two problems though. For one, _other entities don't have this._ When you inflict bleeding on anything else (eg. getting a critical hit with a sword) they have the normal swirly magic potion particles that come from any other effect. 
For two, _the player also still has these swirly particles, but combined with the blood particles._ This gets in the way like other potion effects, but because of how often you have the bleeding effect in a normal game of survival it can get extremely annoying to constantly have those swirly particles blocking your vision in combat.

My proposal is that you replace this particle effect with the custom player one so that all entities have that bleeding effect. It's also a lot more discernable over other generic potion effects and will help players know whether their enemies are bleeding or not. It also gets rid of that nasty swirly effect you see when you're inflicted with bleeding.

**Comment by Majrusz** [comment]
I finally did it and in the next update all mobs will have custom blood particles :)
