### ISSUE TITLE
[Feature Request] Configuration for which dimension triggers modes

### ISSUE THREAD

**Issue by CalaMariGold** [Majrusz/MajruszsProgressiveDifficultyMod#37]
I'm creating a modpack with a bunch of different dimensions and I'd love to use this mod. However, I'm having the player spawn in the Nether first. I'd like to change the dimension that triggers Expert Mode, as well as a dimension trigger for Master Mode.

This would really help for modpack devs and allow for some creative packs :D

Thank you! <3

**Comment by Majrusz** [comment]
It took me a while, but in the next update it will be possible to choose which entity/dimension triggers the expert and the master modes.
