### ISSUE TITLE
[Incompatibility] Mod crashing with Better Animals Plus mod

### ISSUE THREAD

**Issue by sharlin073** [Majrusz/MajruszsProgressiveDifficultyMod#38]
[crash-2021-04-06_01.18.48-server.txt](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/6260427/crash-2021-04-06_01.18.48-server.txt)

Disabling (yes, it is not enabling...strange...) "do_spawning" config (I did for butterfly/dragonfly) in Better animals plus mod somehow crashes the game.

I asked the author there, but it seems like the issue needs to be fixed here.
(They said an item with negative damage is given to a mob, but I guess I don't have any items like that...)

I'm not sure this is fixable, but reporting here :)

**Comment by Majrusz** [comment]
Thanks for reporting this bug, it will be fixed in the next update.
