### ISSUE TITLE
Pillager's Wolves don't despawn like other hostile mobs after all players have left the area.

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [Majrusz/MajruszsProgressiveDifficultyMod#40]
Majruszs Difficulty Version: 0.5.2
Majruszs Library Version: 1.5.0
Forge Version: 36.1.4
Minecraft Version: 1.16.5

Hi,
I've noticed when testing the increased difficulty modes this mod offers that when I have moved away from the area and came back after a while, the pillager's wolves that had spawned were still there and had not despawned as you would expect from any other hostile mob. After leaving the area and returning back a short while later their pillager leader had despawned and the wolves would just be left to wander aimlessly and would stick around forever because they never despawn.

This could eventually lead to a build up of these mobs over time which could end up taking up the mob cap and potentially causing a lot of lag if big enough groups are allowed to build up.
![2021-04-16_21 04 27](https://user-images.githubusercontent.com/64381954/115079455-1c133c00-9ef9-11eb-9f33-f305f3804653.png)
![2021-04-16_21 04 17](https://user-images.githubusercontent.com/64381954/115079479-23d2e080-9ef9-11eb-846b-b21e2187e979.png)
They should be able to despawn to be consistent with every other hostile mob that exhibits this behaviour (E.g Pillagers, Zombies, Skeletons). This will also help performance in the long run too.

**Comment by Majrusz** [comment]
Thanks for reporting this bug, it will be fixed in the next update.

**Comment by The-Bernician-Lamb** [comment]
Awesome! Thanks for this!
