### ISSUE TITLE
Wither kill dropped 16 bags even though it was off.

### ISSUE THREAD

**Issue by DaddyP1G** [Majrusz/MajruszsProgressiveDifficultyMod#41]
The "This item is disabled and is not available in Survival Mode!" was still on the item, but the players were able to open it still.  It also dropped 16 bags. 

This is a modded test Server.  Possible interaction with End Remastered?  It changes Wither Loot Table.  That is why I had to turn the bag off.   Tested on Single player and didn't drop.

**Comment by Majrusz** [comment]
Thanks for reporting this bug, it will be fixed in the next update.
