### ISSUE TITLE
[Bug Report/Suggestion] Elite skeletons spawn only in light level 7 and below

### ISSUE THREAD

**Issue by DeckerExpert** [Majrusz/MajruszsProgressiveDifficultyMod#42]
I don't know if this "feature" is intentional or not, but I would like it if the elite skeletons were to spawn in light level 7 and below, or at the very least, make this configurable in the config.

I hope I get a response soon.

**Comment by Majrusz** [comment]
Hi, firstly sorry for late response and secondly the Elite Skeleton spawns under the same conditions as other monsters in the game. I will consider adding the possibility of changing this in the future.

**Comment by DeckerExpert** [comment]
Huh, that's odd. In a server I'm running, elite skeletons keep spawning even after we spawn proof everything with torches; I even made a room with a literal torch floor and they still spawn. Doesn't that mean this is a bug? 
Btw, this is my server and mod versions:
Minecraft: 1.16.4
Forge: 35.1.37
Progressive difficulty: 0.5.1
 Majrusz's Library: 1.4.0

**Comment by Majrusz** [comment]
Ohh, everything is clear now. This bug has been fixed in version 0.5.2. :)
