### ISSUE TITLE
[Feature Request] "Bleeding" Add Config option to make bleeding deplete naturally

### ISSUE THREAD

**Issue by ranenvious** [Majrusz/MajruszsProgressiveDifficultyMod#43]
As it stands bleeding just self-refreshes making it last practically indefinitely if a bandage isn't used. As far as I can tell there isn't even a config option to turn this off and given I have several other mods, such as first-aid, this makes bleeding just that extra little bit of absolute torment. (also, another thing that would be cool is if there was compat between first aid and the bleeding affect, so singular limbs would be damaged instead of it just being random. )

**Comment by Majrusz** [comment]
Hi, firstly sorry for late response and secondly it was a bug and it should not happen. It will be fixed in the next update.
