### ISSUE TITLE
[Bug Report] Conflict with End Remastered

### ISSUE THREAD

**Issue by litjohn50** [Majrusz/MajruszsProgressiveDifficultyMod#44]
MPDM: 0.5.3
Forge:36.1.4
Minecraft:1.16.5

Problem:
The End Remastered Mod lets you have to explore the minecraft world to unlock the end by getting Custom ender eyes. One of those Ender eyes you have to kill a Guardian to Obtain. 

But it seems that your mod is overriding the Guardian loot Table for the loot Boxes. Making these eyes unobtainable which makes the game unwinnable.

**Comment by litjohn50** [comment]
This will be fixed just by changing the true to false
`		TreasureBagManager.addTreasureBagTo( EntityType.ELDER_GUARDIAN, Instances.ELDER_GUARDIAN_TREASURE_BAG, false );
		TreasureBagManager.addTreasureBagTo( EntityType.WITHER, Instances.WITHER_TREASURE_BAG, false );
		TreasureBagManager.addTreasureBagTo( EntityType.ENDER_DRAGON, Instances.ENDER_DRAGON_TREASURE_BAG, false );`

**Comment by Majrusz** [comment]
Hi, sorry for late response. This will be fixed in the next update.
