### ISSUE TITLE
[Bug Report/Question] Skeletons in Undead army not seeing the player

### ISSUE THREAD

**Issue by cyco20** [Majrusz/MajruszsProgressiveDifficultyMod#46]
Minecraft: 1.16.5
Forge: 36.1.4

I was adding this to a Valhesia 3 server I have and the skeletons that spawn don't seem to see me or defend themselves when attacked. I know that mods act weird when 200+ are used at once, but do you know what could be the problem?

Vid of the problem:
https://drive.google.com/file/d/1dgHCxyGbWZNOznbEMkhzUs9H_K6xREa1/view?usp=sharing

**Comment by Majrusz** [comment]
Hi, sorry for late response. Do you have any mods that changes AI of monsters? Because probably new AI has lower priority to attack the player than to move to the goal position.

**Comment by Blacksky649** [comment]
I'm having the same issue. It applies to all skeletons from the raid. Only AI mod I have is aiimprovement. All other skeletons spawned in the world operate normally

Update: Seems to be all mobs from the raid have prio to head towards the marker over attacking players

**Comment by rooben777** [comment]
Happens to me aswell, for now I am trying to disable elite skeletons in the configs in hope that they wont appear during the raid, I sure do hope it will be fixed soon, this is truely an awsome feature

**Comment by Blacksky649** [comment]
After a lot of testing I found the issue. Performant (mod) seems to ruin the goal AI of this mod. I tried turning off all features in Performant's config to locate the issue and nothing changed. Hopefully this helps

**Comment by Majrusz** [comment]
Thanks @Blacksky649 for finding the mod that caused this bug! It helped me a lot and I was able to fix it. In the next update this will work properly. :)
