### ISSUE TITLE
Config File mistake

### ISSUE THREAD

**Issue by nateheron** [Majrusz/MajruszsProgressiveDifficultyMod#48]
In the config file there are two changeable effects called "#Spider inflicts poison."

	#Spider inflicts poison.
	[Features.EndermanTeleport]
		#Is this feature enabled?
		is_enabled = true
		#Chance of this feature to happen. (this value is scaled by Clamped Regional Difficulty)
		#Range: 0.0 ~ 1.0
		chance = 0.5

	#Spider inflicts poison.
	[Features.SpiderPoison]
		#Is this feature enabled?
		is_enabled = true
		#Chance of this feature to happen. (this value is scaled by Clamped Regional Difficulty)
		#Range: 0.0 ~ 1.0
		chance = 0.25

I have to assume that the top one is meant to be the effect of how players teleport when attacked.

**Comment by Majrusz** [comment]
Thanks! The comment will be corrected in the next version :)
