### ISSUE TITLE
Mobs in structures that are assigned to it (Piglins in bastions, villagers in village, Illagers in mansion or even illagers durring raids) has vanila hp that is not modified

### ISSUE THREAD

**Issue by toffi3** [Majrusz/MajruszsProgressiveDifficultyMod#49]
i've seen the issue about the mod that the mobs in the vanilla raid and for example piglin brutes or piglins in bastion or drowneds in the ocean ruins does not get extrahp from modifiers. The bug is even on the version 0.1.0 so it's from the beggining of the mod. Here's the recorded example by me on version 0.1.0 https://www.youtube.com/watch?v=XWJ3mrnI0No&feature=emb_title

**Comment by toffi3** [comment]
Sorry for spaming about it but i really want you to fix it

**Comment by Majrusz** [comment]
In the next update it will work properly. :)
