### ISSUE TITLE
Stuck on creating world screen with latest update

### ISSUE THREAD

**Issue by bigbull646** [Majrusz/MajruszsProgressiveDifficultyMod#52]
The Issue I'm experiencing is really hard to replicate because the mod doesn't crashes my game, instead the percentage that shows that the world is being generated stops advancing but everything works fine, even when I check on the task manager it shows that Minecraft is indeed using both RAM and CPU, but it just stays still on the same percentage without doing anything, the only way to close it is by stop it via task manager, and no crash log is generated. 
After downgrading both the mod and the library the problem stopped. 
if there is any more information I could provide please let me know and I do my best to provide it

**Comment by Majrusz** [comment]
Have you tried creating a world with my mod only?

**Comment by GnomTocha** [comment]
The same problem, but sometimes the bug happens differently. While traveling the world the chunks stop loading and the one probe writes that the server is not responding. Also this problem can be seen using the World Pre Generator mod. Chunks just stop loading. The problem happens on a modified build. I am looking for a conflict.

**Comment by GnomTocha** [comment]
> The same problem, but sometimes the bug happens differently. While traveling the world the chunks stop loading and the one probe writes that the server is not responding. Also this problem can be seen using the World Pre Generator mod. Chunks just stop loading. The problem happens on a modified build. I am looking for a conflict.

In my case, the conflict arises with mod forbidden_arcanus-16.2.0-beta-3 (https://www.curseforge.com/minecraft/mc-mods/forbidden-arcanus/files/3225554).

**Comment by bigbull646** [comment]
> Have you tried creating a world with my mod only?

I tried by itself and it works just fine, just as GnomTocha said seems to be an issue with forbidden and arcanus and therefore the issue might as well be on their end. for what I understand that version is somewhat of a rewrite from the initial idea of the mod and might have some issues and could change a lot by the time of a release version. 

Thanks for the quick reply and just wanted to let you know that your work is great. thanks for the mod.

**Comment by Majrusz** [comment]
Probably that mod causes this bug, anyway when I tried to reproduce this error on forge version 36.1.0 the error did not occur (or is very rare). I suggest that you use this version.

**Comment by GnomTocha** [comment]
> Вероятно, этот мод вызывает эту ошибку, в любом случае, когда я попытался воспроизвести эту ошибку в кузнице версии 36.1.0, ошибка не возникла (или возникает очень редко). Предлагаю вам использовать эту версию.

Thanks for the answer. By the way, the problem appears in Forge 36.1.23.

**Comment by bigbull646** [comment]
After further testing I can safely say that the newest version of the mod works like a charm with Forge 36.1.23. and the issue with chunk loading in previously created worlds is no longer there, furthermore integrates perfectly with the following mods which are part of my modpack

[Mod List.txt](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/6573145/Mod.List.txt)

Forbidden and Arcanus beta however is still messing world generation. but like I said before, that might as well be on their end.

Looved the new content and the creeperlings both hate them and love them.
please do continue doing life in my modpack miserable, you've been doing an amazing job.

**Comment by Majrusz** [comment]
Haha, thanks for your feedback! :)
