### ISSUE TITLE
[suggestion]Add a recycle mechanism of item like "giant seed" and "lucky rock".

### ISSUE THREAD

**Issue by rtxyd** [Majrusz/MajruszsProgressiveDifficultyMod#54]
Now these two functional items are just two functional items, player get them, then not need to get again. Extra of these two items are useless. Will you consider to add a recycle mechanism like trigger limits of one item, or make them be materials to craft consumables like potion? This will make extra of them useful and more balanced.

**Comment by Majrusz** [comment]
I have added two new mechanism for these items. First is that now they have an effectiveness bonus and it is worth getting another duplicate with a better bonus, and the second is that they can now be sold in villager trade.

**Comment by rtxyd** [comment]
This update is great, and most close to vanilla!
