### ISSUE TITLE
"Structures not correctly registered to flatlands generation" breaks datapacks in saves after first save and reload

### ISSUE THREAD

**Issue by Darkmega18** [Majrusz/MajruszsProgressiveDifficultyMod#55]
I have come across one heck of an issue which only surfaced when I installed the compact machines mod with this. The brunt of the issue and the eventual testing can be found here:

https://github.com/CompactMods/CompactMachines/issues/476

The versions can be seen in the pictures if you really need them. But I'm told that the issue is:

> I've narrowed down the issue to a bug with majruszs_difficulty. This needs to be reported to them. The issue is they are not correctly registering their structures to the flat world generation, which Compact Machines utilize for the Machine dimension. This is not an issue with Compact Machines and needs to be reported to them.

> Relevant logs with Blame installed: https://gist.github.com/SizableShrimp/2113d067d2bd69210474bf8e9b93cdb5

**Comment by Majrusz** [comment]
What version of modification and forge are you using?

**Comment by Darkmega18** [comment]
it was:
MC 1.16.5
Forge: 36.1.23
Difficulty: 0.6.1
library: 1.6.0

**Comment by Darkmega18** [comment]
did this get fixed in the latest update?

**Comment by Majrusz** [comment]
Unfortunately no, try using Forge version 36.1.0 because with the latest .24 and .23 versions there are several problems.

**Comment by Darkmega18** [comment]
I cannot, 

Because several mods I use are built against higher versions innately in their most up to date states. :V and those in turn will backdate other mods which rely on the new versions of the mods in their own recent updates due to new features in them and such.

**Comment by lartts** [comment]
Have a similar problem here

**Comment by Darkmega18** [comment]
I'm back to bother you again, Majrusz... it's still happening. 

but now it's with thermal series in with FORGE 36.2.2. and I need thermal a lot more than I did need compact machines.

Please take a look at this again and update the mod. it's likely having issues with the same error.
https://pastebin.com/b9FzSP3J

I only realized because this section of my latest log makes mention of flat generator. and I recall this being the reason I came here before with the blame mod reporting the end structures weren't being done right.

**Comment by Darkmega18** [comment]
G'day @Majrusz I'm not sure what to do here, but in my pack, The difficulty mod has started causing datapack issues again. I'm not sure if they're the same ones, but the thing in common is a similar mention about a flatlands generator in the stack trace which was a similar issue to what I originally reported.
https://pastebin.com/b9FzSP3J

But now the version is:
Forge: 36.2.2
majrusz-library 1.16.4-2.0.1
majruszs-difficulty 1.16.4-1.1.0

removing difficulty mod from the modpack stops the occurence, so there is definitely something within the mod contributing to the issue and those structures are the only leads I have.

**Comment by Darkmega18** [comment]
I narrowed it down to an updated version of dimensional dungeons. I was presume it's a very similar issue to what compact machines had. because dimensional dungeons ALSO generates it's dimensions and dungeons within a flatlands generator or "empty" world basically. But strangely, the bug does not present when you yourself generate the world as a flat generator. Which is why it went undetected for a little while as I had been using a void test world for some time. :V
