### ISSUE TITLE
Evoker totem feature no longer working

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [Majrusz/MajruszsProgressiveDifficultyMod#56]
Forge Version: 36.1.31
Minecraft Version: 1.16.5
Majruszs Difficulty Version: 0.7.0
Majruszs Library Version: 1.7.0
Latest Log: https://gist.github.com/NJL5390/273c40455a6a57f8aa6533901723fe06

Hi,

I noticed that in a recent version the Evoker totem feature (Where the evoker uses a totem of undying to save himself) is no longer working, where it was working when I first started using this mod. 

I'm not sure why this feature isn't working anymore, maybe one of the recent updates or forge changes broke it? I'm not sure. I know that this issue still occurs without any other mods installed though. If you need any more information about this issue then let me know and I'd be happy to provide it.

Thanks for the great mod!

**Comment by Majrusz** [comment]
Thanks, it really doesn't work. This will be fixed in the next update.
