### ISSUE TITLE
[Suggestion] Compatibility with Tinkers Construct

### ISSUE THREAD

**Issue by masternetra** [Majrusz/MajruszsProgressiveDifficultyMod#58]
Currently as it stand the lucky rock doesn't effect tinker's tools nether the tinker's pickaxe nor sledge hammer (which mines 3x3x1), would like to see it effect mining with the tools.

**Comment by Majrusz** [comment]
Lucky Rock was moved to [a different mod](https://www.curseforge.com/minecraft/mc-mods/majruszs-accessories), but in the next update, there will be compatibility with Tinkers Construct. :)

**Comment by masternetra** [comment]
Is the compatibility in the 1.4 you just released or in 1.5 that will be released later?

**Comment by Majrusz** [comment]
It has been added in the 1.0.4 version
