### ISSUE TITLE
Elite Skeletons spawn mid air on the nether

### ISSUE THREAD

**Issue by Allomere** [Majrusz/MajruszsProgressiveDifficultyMod#6]
https://youtu.be/VuMUHubiqT4 <- vido showing the bug
After you enter the nether Elite skeletons will start spawning mid-air, sometimes leading to their deaths

**Comment by Majrusz** [comment]
Which version of the mod you are currently using? Because in the latest update 0.2.2 it should be fixed.

**Comment by Allomere** [comment]
Seams like i was using 0.2
Im sorry, i generally check if i'm using the latest version or not before reporting a mod's issue, i will update it

**Comment by Majrusz** [comment]
There is no problem :)
