### ISSUE TITLE
Spawn bonuses not applying in the Overworld when a mob is spawned by In control's Spawning system

### ISSUE THREAD

**Issue by The-Bernician-Lamb** [Majrusz/MajruszsProgressiveDifficultyMod#61]
Majrusz's Progressive Difficulty version: 1.1.0
Majrusz's Library version: 2.0.1
In Control Version: 5.1.9

Hi,

I've noticed that with the latest update to this mod, the spawn bonuses sometimes weren't being applied to mobs that spawned in the overworld. After looking into it further I found that the mobs that weren't having bonuses applied were being those that I had written spawn rules for via a mod called In Control (https://www.curseforge.com/minecraft/mc-mods/in-control). The ones that spawned via regular means or via a spawn egg or monster spawner had the bonuses applied correctly:

Mob spawned via Spawn egg:
![2021-07-03_15 28 01](https://user-images.githubusercontent.com/64381954/124396022-2d513500-dcff-11eb-8c86-1bfa3ae7c38c.png)

Mob spawned via In Control's spawning system:
![2021-07-03_15 28 16](https://user-images.githubusercontent.com/64381954/124396036-44902280-dcff-11eb-9512-60de2a57ff66.png)

This also only seemed to happen when mobs were spawned in the Overworld. In other dimensions such as the nether, the end or the twilight forest, the spawn bonuses were applied correctly and there were no problems. 

This issue with In Control only seemed to start happening as of the latest update to this mod and was working fine prior to this update. If I can be of any further assistance with this issue then just let me know and I'd be happy to help in whatever way I can.

Thanks for the great mod!

**Comment by Majrusz** [comment]
Should be fixed in latest release for 1.19.1
