### ISSUE TITLE
Bandage recipe

### ISSUE THREAD

**Issue by seanlsims** [Majrusz/MajruszsProgressiveDifficultyMod#62]
Is it possible to add compatibility with other types of string like [Silent Gear](https://www.curseforge.com/minecraft/mc-mods/silent-gear)'s sinew fiber?

**Comment by Schummel-8** [comment]
You can change the crafting recipe with a datapack to accept different items via a tag.
Then you just have to define what items you want in that tag, also via datapack.

**Comment by Darkmega18** [comment]
> 
> 
> You can change the crafting recipe with a datapack to accept different items via a tag.
> Then you just have to define what items you want in that tag, also via datapack.

that. indeed.
