### ISSUE TITLE
Suggestion: Config for mobs or whole dimensions to not get the health/damage boost

### ISSUE THREAD

**Issue by Schummel-8** [Majrusz/MajruszsProgressiveDifficultyMod#63]
Would be really helpful for modpack makers to exclude certain mobs or dimensions from the damage/health multiplier.
So like bosses don't have 500 hearts instead of 400 or a dimension is set to be always on normal mode and not increase in difficulty since all gear is getting nerfed except the gear from the dimension itself (Blue Skies Mod).

I'm aware that scaling health exists and can deal with this kind of requirement but i really like the stage system of your mod and want to use it.
Please let me what you think about this suggestion.

**Comment by Majrusz** [comment]
Cool idea, I will add a config for that in the future

**Comment by Majrusz** [comment]
After a long time, I finally managed to do this eb515c4f2a73d172a96906ff8b5881ae9679e811 d474f58a7ae1418344fd3c6c03c8dfea835ccb93 Soon a new update will be available
