### ISSUE TITLE
1.17.1 crash

### ISSUE THREAD

**Issue by Tyrius1** [Majrusz/MajruszsProgressiveDifficultyMod#64]
https://pastebin.com/e4gcg3cP
https://pastebin.com/P3PVkXip

When attempting to add the mod into my current profile i get a crash i usually only get the one regarding the bleeding effect but the top log seems to be a different crash. Unsure if its relevant but figured id share as well

minecraft 1.17.1
forge 37.0.22
majruszs-difficulty-1.17.1-1.2.0
majrusz-library-1.17.1-2.1.0

**Comment by Majrusz** [comment]
Fixed, check out the new 1.2.1 version and thanks! :)
