### ISSUE TITLE
I think this mod is causing an infinite loop that's crashing my server

### ISSUE THREAD

**Issue by Norevex** [Majrusz/MajruszsProgressiveDifficultyMod#67]
I am using majruszs-difficulty-1.16.4-1.1.0 and I believe it to be the reason my server is crashing, the server crashed whenever I enter the nether and I get the error message "a single server tick took 60.00 seconds". I will link the crash report as well as my mod list as it might be conflicting with another mod.
Mod list: https://ibb.co/mRvX0zS
Crash log: https://drive.google.com/file/d/1SZV5xtmUvRQ9K3_Fr71whHxkYB2t-yPb/view?usp=sharing

**Comment by Majrusz** [comment]
Fixed, and it will be available in the next release :)
