### ISSUE TITLE
java.lang.reflect.InvocationTargetException: null

### ISSUE THREAD

**Issue by Baggytrousers27** [Majrusz/MajruszsProgressiveDifficultyMod#68]
majrusz-library-1.17.1-2.2.0
majruszs-difficulty-1.17.1-1.2.2
Forge 17.17.1-37.0.31(33)

Majrusz's Progressive Difficulty (majruszs_difficulty) has failed to load correctly java.lang.reflect.InvocationTargetException: null

[Crashlog](https://pastebin.com/1wmT24vs)

**Comment by Majrusz** [comment]
Fixed, it will be working fine in the next 1.2.3 version
