### ISSUE TITLE
World generation is hanging together with Forbidden Arcanus

### ISSUE THREAD

**Issue by lebagvondouche** [Majrusz/MajruszsProgressiveDifficultyMod#69]
Using these two mods together and while is_spawning = true the world generation hangs. Attaching the thread dump from VIsualVM. Not sure which mod is the culprit here.

It works if I disable all spawns from Majrusz's.

https://pastebin.com/FikRbLwR

Forge 36.2.2 (Saw the same error on previous versions as well)
Majrusz's Library 2.0.1
Majrusz's Difficulty 1.1.0
Forbidden Arcanus 2.0-beta 4

**Comment by ghost** [comment]
I have the same problem.
Worker Main 27
https://hastebin.com/dedecokube.properties

**Comment by HockeyZman2000** [comment]
https://github.com/stal111/Forbidden-Arcanus/issues/198

I made an issue on their GitHub as well because I'm having the same issue here and don't know which mod is the culprit here

**Comment by Brycey92** [comment]
I've got the same issue

**Comment by Ozzi-Hero** [comment]
Just discovered this bug while making my modpack, wasn't aware it was caused by having both F&A and this mod. Adding it to an existing world prevents new chunks from generating.

**Comment by Majrusz** [comment]
Thanks for reporting that, it was fixed in recent releases for 1.18.2 and 1.19
