### ISSUE TITLE
Undead Army soldiers get stuck inside of trees from time to time

### ISSUE THREAD

**Issue by Not-February** [Majrusz/MajruszsProgressiveDifficultyMod#70]
![image](https://user-images.githubusercontent.com/13922447/130017553-36f3f24a-d864-473b-a6e8-77dd5aaf9bac.png)

You have to actually break the leaves to get them out, and they can stay there pretty much indefinitely even after the army's raid has ended because they won't burn up.

**Comment by Majrusz** [comment]
Fixed, in the next version it will no longer be an issue
