### ISSUE TITLE
World is starting on expert mode from the start

### ISSUE THREAD

**Issue by Darkmega18** [Majrusz/MajruszsProgressiveDifficultyMod#71]
My world is for some reason triggering itself to expert mode immediately upon a mob spawning near the player or when world creation, or just sometime really very early that you don't realize.

I have the any dimension settings turned off and both dimension triggers left at "none".
My expert mode is triggered by killing one of several mini-bosses. while Master mode is triggered by killing some of the larger end gamey bosses like wither or ender dragon.
Started happening I think perhaps it was after one of the last two updates.
Current version in my pack is:
majruszs-difficulty-1.16.4-1.1.0.jar
With library:
majrusz-library-1.16.4-2.0.1.jar
MC and Forge is: 1.16.5-36.2.2

Here is a copy of my config file for you to look at if theres anything I'm perhaps doing wrong that I'm not noticing.
[majruszs-difficulty-common - Copy.txt](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/7027635/majruszs-difficulty-common.-.Copy.txt)

**Comment by Majrusz** [comment]
Config is fine, I guess some other mod is causing this bug, because it looks okay in code :(

**Comment by Darkmega18** [comment]
Ai-yi-yi. Thats gonna be a painful one to hunt down. D:

**Comment by Darkmega18** [comment]
@Majrusz from a preliminary test, refreshing the config without my bosses placed in it and without any changes seems to normalize it just fine.

I'm not sure if maybe there is something odd going on with the "any dimension" checker? since I turn that off in my modpack usually to instead have it be boss based. since some players can start in the nether or end or atum due to origins that I have created.

I'm going to slowly make changes until it comes back to it's original state and test a round spawning mobs until something snaps.

**Comment by Darkmega18** [comment]
ok, the issue resurfaced when I changed the boss lists. Something is going wrong there. I spawned in, and spawned a spider, it had double health. doing gamestate back to normal fixed it. not sure if it just hates my list of bosses or something is tripping it.

confirmed that taking off my expert mode list that has modded entities in it seems to have stopped the issue.
