### ISSUE TITLE
[Feature Request / Suggestion ] Per-player difficulty for dedicated servers

### ISSUE THREAD

**Issue by Not-February** [Majrusz/MajruszsProgressiveDifficultyMod#72]
For dedicated server environments, it's pretty punishing for newer players who join later than others to have to deal with Expert or Master Mode right off the bat when they weren't there to get equipment before scaling the difficulty.

Some kind of option to calculate the difficulty surrounding a player based on which players have done what would be a good compromise, I think.

**Comment by GrigLog** [comment]
Ive tried implementig it today and damn, it requires rewriting like 60% of the mod and the library...

**Comment by Majrusz** [comment]
Hello, it took me a while, but recently I rewritten my mod and finally added it! Thanks for the suggestion and check out the latest 1.9.0 release
