### ISSUE TITLE
[1.17.1] Crash when loaded with Wonderful Enchantments 1.5.0

### ISSUE THREAD

**Issue by Baggytrousers27** [Majrusz/MajruszsProgressiveDifficultyMod#73]
Forge 37.0.65
majrusz-library-1.17.1-2.4.0
majruszsaccessories-1.17.1-0.3.0
majruszs-difficulty-1.17.1-1.2.3
wonderful-enchantments-1.17.1-1.5.0

Majrusz's Progressive Difficulty (majrusz_difficulty) has failed to load correctly

java.lang.reflect.InvocationTargetException: null

[Crashlog](https://pastebin.com/uJYW3dnn)

**Comment by Majrusz** [comment]
Fixed in the latest 1.2.4 version :)
