### ISSUE TITLE
Had this crash in my pack after jumping from the void into the end (falling through mod)

### ISSUE THREAD

**Issue by Mr-Syntax** [Majrusz/MajruszsProgressiveDifficultyMod#76]
dunno if this is the cause
ive been able to do this several times (jumping into the nether like that)  but all of a sudden it crashed after the first few chunks in the nether :-/
[crash-2021-10-18_00.57.48-server.txt](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/7361013/crash-2021-10-18_00.57.48-server.txt)

https://www.curseforge.com/minecraft/modpacks/chosencraft

**Comment by Mr-Syntax** [comment]
i think actually the cause would be that i hadent entered the nether before going to the end cause i was in creative mode and then when i got the achievment it crashed

but in my pack actually going to the end before the nether isent possible because of the End Remastered mod so its not the biggest issue, all tho it might be an issue if it was on a server

**Comment by Majrusz** [comment]
Thanks for reporting that, fixed in recent updates
