### ISSUE TITLE
Does not work on version 1.18 - Requires Forge v39+ (hence won't load on 1.18 which is Forge v38)

### ISSUE THREAD

**Issue by SheerAwesomeness** [Majrusz/MajruszsProgressiveDifficultyMod#80]
As title describes, this mod while tagged as 1.18 and 1.18.1 only loads in 1.18.1 - same issue with the library mod.

**Comment by Majrusz** [comment]
Thanks for reporting this, in the latest version 1.4.1 it is possible to use Forge v38 :)
