### ISSUE TITLE
Majrusz Progressive Difficulty Causing "Freezing"

### ISSUE THREAD

**Issue by Jaden99c** [Majrusz/MajruszsProgressiveDifficultyMod#81]
Are there any incompatabilities with this mod? Like the title says, it has been causing freezing. Everything works fine for a little, but as soon as I walk to a specific point (in this case, a mineshaft from Yungs Better Mineshafts), I can break blocks but they dont drop anything, water sources cant be stopped by blocking them off, mobs can be hit but wont take damage or try to hurt you, etc.... I try to quit the world and it gets stuck on Saving World. Have to force quit from task manager. Once I reload the world, it loads me back to a point where I never entered the mineshaft. As soon as I removed this mod everything worked fine. I am on 1.16.5 Forge - 36.2.22 
Here is my mod list:
Neapolitan (by TeamAbnormals)
Spartan Weaponry (by ObliviousSpartan)
Library of Exile (by mcrobertx22)
Waystones (by BlayTheNinth)
Cloth Config API (Forge) (by shedaniel)
Wandering Bag (by Furti_Two)
Traveler's Titles (Forge) (by YUNGNICKYOUNG)
Divine Missions (by mcrobertx22)
No Recipe Advancements (by MutantGumdrop)
Better Animations Collection (by Fuzs_)
Arachnid Rancher (by TillaSiren)
Goblins & Dungeons (by superlord_9362)
Mutant Beasts (by Chumbanotz)
RevampedWolf (by bagu_chan500)
Extra Boats (by TeamAbnormals)
The Undergarden (by Quek04)
Config Menus for Forge (by Fuzs_)
Motschen's Better Leaves (by Motschen)
Embellished Stone (Advancement Plaques) (by Grend_G)
Obfuscate (by MrCrayfish)
Client Tweaks (by BlayTheNinth)
Polymorph (Forge) (by TheIllusiveC4)
xali's Enchanted Books (by xalixilax)
Stalwart Dungeons (by Furti_Two)
Apotheosis (by Shadows_of_Fire)
Aquamirae (by ObscuriaOfficial)
Better Compatibility Checker (by Gaz_)
Inventory HUD+ (by dmitrylovin)
Simple Shops (by wolforce)
Nourished Nether (by MuffinsDev)
Bountiful (Forge) (by ejektaflex)
Passable Foliage 🌳 (by Snownee_)
JEITweaker (by Jaredlll08)
FTB Quests (Forge) (by FTB)
STONEBORN - Dwarven-Fantasy Inspired UI Overhaul (by Sindavar33)
Butcher's Delight (by onuadan)
FTB Library (Forge) (by FTB)
FTB Teams (Forge) (by FTB)
What Did You Vote For? 2021 mob vote: Glare, Allay and Copper Golem! (by alexandersfunandgames)
Overloaded Armor Bar (by tfarecnim)
Pehkui (by Virtuoel)
Nether's Exoticism (by Furti_Two)
Sons Of Sins (by Furti_Two)
Nature Expansion (by Ddx11__)
Nourished End (by MuffinsDev)
Subterranean Wilderness (by Melonslise)
Structure Gel API (by ModdingLegacy)
AttributeFix (by DarkhaxDev)
Hexerei (by JoeFoxe)
Just Enough Keg (by marblegatekeeper)
Spartan Retextured (by aneckdope)
AutoRegLib (by Vazkii)
Fast Furnace minus Replacement (by tfarecnim)
Blue Skies (by ModdingLegacy)
CraftTweaker (by Jaredlll08)
Village Artifacts (by Lothrazar)
The Afterlight (by Wispearl)
More Villagers (by SameDifferent)
Custom Starter Gear (by brandon3055)
When Dungeons Arise - Forge! (by Aureljz)
Alex's Delight (by NCP_Bails)
Drippy Loading Screen [Forge] (by Keksuccino)
Citadel (by alex_khaan)
Obscuria's Essentials (by ObscuriaOfficial)
Controlling (by Jaredlll08)
Upgraded Netherite (by Rolfmao25)
Tiny Skeletons [Forge] (by Fuzs_)
Blueprint (by TeamAbnormals)
Goblins Community! (by pixelgeist666)
Enchantment Descriptions (by DarkhaxDev)
FancyMenu [Forge] (by Keksuccino)
The Farlanders (by ModdingLegacy)
🔨 Crumbs (Forge) (by Trikzon)
Drink Beer (Forge) (by Lekavar)
Enchant With Mob (by bagu_chan500)
Dungeons Gear (by the_infamous_1)
Dungeons Plus (by ModdingLegacy)
Extended Mushrooms (by thecech12)
The Conjurer (by ModdingLegacy)
Buzzier Bees (by TeamAbnormals)
Fresh Animations (by FreshLX_official)
Item Filters (Forge) (by LatvianModder)
Twist (by foshyjoshy9999)
HT's TreeChop (by hammertater)
Blood Magic (by WayofTime)
Environmental (by TeamAbnormals)
Mowzie's Mobs (by bobmowzie)
Medieval Music[Forge/Fabric] (by someaddon)
Valhelsia Core (by ValhelsiaTeam)
RoadRunner (by MaxNeedsSnacks)
Kobolds Community! (by pixelgeist666)
Just Enough Items (JEI) (by mezz)
Cuneiform (by azmalent)
Druidcraft (by VulpTheHorseDog)
FerriteCore (Forge) (by malte0811)
Toast Control (by Shadows_of_Fire)
UnionLib (by Stereowalker)
Entity Culling Fabric/Forge (by tr9zw)
Wilds (by SpicyBananaModding)
Toad Terror (by Cicoda)
Serene Seasons (by TheAdubbz)
Danny's Expansion (by BottomTextDanny)
LibX (by noeppinoeppi)
Konkrete [Forge] (by Keksuccino)
The Outer End (by BlueDuckYT)
Not Enough Animations (Forge/Fabric) (by tr9zw)
Akashic Tome (by Vazkii)
NoCube's Sea Dwellers (by nocubeyt)
Sky Villages [Forge] (by y4z0n)
Snow! Real Magic! ⛄ (Forge) (by Snownee_)
Tome of Blood (by ToxicMintTea)
Health Pickups & player starting health (by Lothrazar)
Abnormals Delight (by TeamAbnormals)
Earth Mobs (by bagu_chan500)
Untamed Wilds (by raytrace82)
PlayerEx (by clevernucleus)
Magnesium Extras (by TeamDeusVult)
Dungeons Enhanced (by mo6301)
Nature's Compass (by Chaosyr)
Ice & Fire Dragonsteel Weaponry (by DE4THR4SH)
Simple Storage Network (by Lothrazar)
Atum 2: Return to the Sands (by Shadowclaimer)
First-person Model (Forge/Fabric) (by tr9zw)
Greek Fantasy (by skyjay1)
Legendary Tooltips (by Grend_G)
Combustive Fishing (by TheIllusiveC4)
Nether's Delight (by lumpazl)
In Control! (by McJty)
Forbidden and Arcanus (by cesar_zorak)
Personality (by TeamAbnormals)
Eclectic Trove (Legendary Tooltips) (by Grend_G)
Corpse (by henkelmax)
Towers of the Wild: Additions (by Aureljz)
Just Enough Resources (JER) (by way2muchnoise)
Darker Depths (by naterbobber)
Mutant More (by alexandersfunandgames)
Atmospheric (by TeamAbnormals)
Curious Elytra (Forge) (by TheIllusiveC4)
CaveBiomeAPI [Forge] (by blackgear27)
YUNG's Bridges (Forge) (by YUNGNICKYOUNG)
Stoneholm, Underground Villages (Forge) (by TheGrimsey)
Easy Magic [Forge] (by Fuzs_)
Structurize (by H3lay)
Small Ships (by talhanation)
Hunter illager (by bagu_chan500)
Curios API (Forge) (by TheIllusiveC4)
Sapience (by the_infamous_1)
Cartographer (by thevortexFoxTopia)
Kotlin for Forge (by thedarkcolour)
Advancement Plaques (by Grend_G)
Guard Villagers (by almightytallestred)
Better Third Person (by Socolio)
Traveler's Backpack (by Tiviacz1337)
The Abyss II - The Other Side (by y4z0n)
ItemPhysic Full (by CreativeMD)
Stables (by f1ashfyre)
Farmer's Delight Cookbook Addon [0.4 is the last update] (by dalumma)
Better Ender Dragon (by Ricy41)
GeckoLib (by ThanosGecko)
Enhanced Celestials - Blood, Blue, & Harvest (Super) Moons (by Corgi_Taco)
Structures Plus II (by Qra5)
Trick or Treat (by SameDifferent)
Enhanced Mushrooms (Forge) (by team_aurora_modding)
Just Enough Effect Descriptions (JEED) (by MehVahdJukaar)
Carry On (by Tschipp)
Frozen Up (by ninnih_)
Silent Lib (silentlib) (by SilentChaos512)
The Graveyard (FORGE) (by finallion_13)
Catalogue (by MrCrayfish)
Lazy DataFixerUpper(LazyDFU) [FORGE] (by Corgi_Taco)
Ice and Fire: Dragons (by alex_khaan)
Decorative Blocks (by stohun)
Void Totem (by Affehund)
KleeSlabs (by BlayTheNinth)
Immersive Cooking (by CrimsonDragonRider)
Puzzles Lib [Forge] (by Fuzs_)
BetterF3 (by cominixo)
Outvoted (by HowBoutNo)
Decorative Blocks modded compat (by Evo_934)
Excalibur (by Maffhew)
Better Badlands (by team_aurora_modding)
Bookshelf (by DarkhaxDev)
Trading Post [Forge] (by Fuzs_)
Upstream (by Corgi_Taco)
Goblin Traders (by MrCrayfish)
Selene Lib (by MehVahdJukaar)
AI Improvements (by QueenOfMissiles)
Caelus API (Forge) (by TheIllusiveC4)
Eidolon (by elucent_)
Villager Names (Forge) (by Serilum)
Seals (by Buuz135)
Pick Up Notifier [Forge] (by Fuzs_)
Oh The Biomes You'll Go (by AOCAWOL)
Iceberg (by Grend_G)
Relics (by SSKirillSS)
Torchmaster (by xalcon)
Patchouli (by Vazkii)
Feywild (by saphienyako)
Falling Leaves (Forge) (by Cheaterpaul)
Paintings ++ (by AbsolemJackdaw)
Towers of the Wild: Reloaded (by yuesha_yc)
Upgrade Aquatic (by TeamAbnormals)
Quark (by Vazkii)
Mushroom Quest (by Ryukusu)
YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)
CleanCut (by Rongmario)
YUNG's API (Forge) (by YUNGNICKYOUNG)
Trolls Community! (by pixelgeist666)
Castle in the Sky (by songxia23)
XP Tome (by bl4ckscor3)
Connectible Chains [FORGE] (by lilypuree)
Loot Beams (by shiroroku)
Simple Discord RPC [Forge/Fabric] (by hypherionsa)
Curio of Undying (Forge) (by TheIllusiveC4)
Wyrmroost (by Wyrmroost)
Undead Expansion (by Fredzik2)
Paxi (Forge) (by YUNGNICKYOUNG)
Piglin Expansion (by Ddx11__)
Infernal Expansion (by InfernalStudios)
RandomPatches (Forge) (by TheRandomLabs)
Chocolate Fix (by AlcatrazEscapee)
Collective (Forge) (by Serilum)
Jade 🔍 (by Snownee_)
spark (by Iucko)
Caves & Cliffs Backport (by blackgear27)
Chunk Animator (by Lumien231)
Repurposed Structures (Forge) (by telepathicgrunt)
MorePaths (by Belkorin)
YUNG's Extras (Forge) (by YUNGNICKYOUNG)
Created Simple Storage Network (by makzzin)
BetterNether Reforged (by someoneelsewastaken)
Collection of Singiro [FORGE] (by Aiko__Suzuki)
Architectury API (Forge) (by shedaniel)
Aquaculture 2 (by Shadowclaimer)
Bamboo Blocks (by TeamAbnormals)
Origins (Forge) (by EdwinMindcraft)
Savage & Ravage (by TeamAbnormals)
Village Employment (by EnderPreston)
Dark Paintings (by DarkhaxDev)
Farmer's Delight (by vectorwing)
Pyromancer (by nikgub_)
Dynamic View[Forge/Fabric] (by someaddon)
MineColonies (by H3lay)
The Twilight Forest (by Benimatic)
Mouse Tweaks (by YaLTeR)
Caves & Cliffs Backport (Additions) (by jukitita)
Illagers Wear Armor (by almightytallestred)
Farmer's Delight Compats (by burritoeatinghamster)
CreativeCore (by CreativeMD)
L_Ender 's Cataclysm (by mcl_ender)
Spartan Shields (by ObliviousSpartan)
Bad Mobs (by DarkhaxDev)
Clumps (by Jaredlll08)
TRansliterationLib (by tr9zw)
Dead Guys Untitled Deep Dark (by deadguystuffs)
Project: Vibrant Journeys (by OrderedChaosDev)
Charm Reforged (by svenhjol)
End Remastered (by jack_bagel)
Krypton Reforged (by TeamDeusVult)
YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)
Kiwi 🥝 (Forge) (by Snownee_)
Ars Nouveau (by baileyholl2)
Better Mods Button [Forge] (by Fuzs_)
Skin Layers 3D (Fabric/Forge) (by tr9zw)
Survive (by Stereowalker)
Geyser Mod (by przemykomo)
Snow Under Trees (by bl4ckscor3)
Visual Workbench [Forge] (by Fuzs_)
Alex's Mobs (by alex_khaan)
Macaw's Bridges (by sketch_macaw)
Sulfuric (by someoneelsewastaken)
JourneyMap (by techbrew)
FastWorkbench Minus Replacement (by tfarecnim)
Just Enough Professions (JEP) (by Mrbysco)
Farmer's Delight Integration (by iku_tv)
Supplementaries (by MehVahdJukaar)
FTB Backups (Forge) (by FTB)
Equipment Compare (by Grend_G)
FTB Chunks (Forge) (by FTB)
The Abyss LPM Integration (by y4z0n)
Magnesium (by someoneelsewastaken)
Omnis (by theOGQueso)
Placebo (by Shadows_of_Fire)
Ogres Community! (by pixelgeist666)
Magnesium Dynamic Lights (by TeamDeusVult)
Cherished Worlds (Forge) (by TheIllusiveC4)
Item Highlighter (by Grend_G)
Treasure Bags (by SilentChaos512)
Dungeons Mobs (by the_infamous_1)
Bayou Blues (Forge) (by team_aurora_modding)
Better Advancements (by way2muchnoise)
BetterEnd Reforked (by someoneelsewastaken)
The Endergetic Expansion (by TeamAbnormals)
Whisperwoods (by itsmeowdev)
Champions (by TheIllusiveC4)
Straw Golem Reborn - Forge (by CommodoreThrawn)
BetterDefaultBiomes (by Xratedjunior)
Traveler's Index (by idrae_)
Village Spawn Point (Forge) (by Serilum)
Creatures and Beasts (by rubyr1derr)

I really want to add this mod to the pack because I love it, but I think it causes a majority of my bugs in game. Thanks for any help

**Comment by Jaden99c** [comment]
Forgot to mention it does not give me a crash report or anything. Im just forced to close application and start over again

**Comment by guivnf** [comment]
had the same issue, seems to be conflicting with ice and fire for some reason

**Comment by Jaden99c** [comment]
> had the same issue, seems to be conflicting with ice and fire for some reason

interesting. I hope they can solve this issue because I would love to see these mods work together

**Comment by snarkbait66** [comment]
this happens to me also, twice, as I had forgotten that it did it to me a few months ago, so I added this mod back again the other day, and nothing but problems. You get a few hundred blocks from spawn and the server freezes, but you are still moving around, and you have to shut minecraft down manually with end task.

**Comment by sozoteki** [comment]
Yeah, I had 150+ mods and the very same thing happened to me. When I remove this mod it went back to normal. I don't have Ice and Fire installed but I question does it have any conflicts with any mods that new mobs into the game or mods that override vanilla stuff like Forbidden Arecanus and Apothesis (I love those two mods). 
I kinda want to know what's causing the crashes and falling into the void because I really want to add this mod to my mod pack so I can continue dying in hardcore mode till I get better.

**Comment by Majrusz** [comment]
Thanks for reporting that, hopefully fixed in 3cdc08ef6af2fee7c171ea4ca2118aca1122c3ce and soon will be available in the next update
