### ISSUE TITLE
[1.18] Random spawners appear in world due to the undead army

### ISSUE THREAD

**Issue by LeoBeliik** [Majrusz/MajruszsProgressiveDifficultyMod#83]
[majrusz-library-1.18.1-2.7.1] [majruszs-difficulty-1.18.1-1.4.1] [1.18.1 - 39.0.16]
Sometimes when I leave the area of the undead army raid, random spawners appear in the zone, so far only skeleton spawners, first I though it was a single use kind of spawner but they work like normal vanilla spawners.

**Comment by HelixCreations** [comment]
This could be the same thing I am having on my server. Except for its Zombies. Do you have a very large number of Skeletons?

**Comment by LeoBeliik** [comment]
it was one of the last waves of the undead raid, but dunno if you'll consider that a large number, tho it happened once next to my skeleton farm too

**Comment by Majrusz** [comment]
I decided to completely remove that feature from the Undead Army so it is not an issue anymore
