### ISSUE TITLE
Large Amount of Zombies Spawning 

### ISSUE THREAD

**Issue by HelixCreations** [Majrusz/MajruszsProgressiveDifficultyMod#85]
So we are having a large issue with the Zombies spawning way too much in Cave Systems. and when they do spawn they spawn in 20-30 of them.  

Using Spark to detect what is causing issues in our server and it's just Zombies.

MC 1.18.1 - Majruszs-Difficulty-1.18.1-1.4.1.jar

I have disabled the Spawning of the Undead Army for Now and will see if Zombies will keep spawning or not.

![image](https://user-images.githubusercontent.com/54270298/150631770-675f9bec-54e4-4929-ad8d-a35f6b6c7e70.png)

![image](https://user-images.githubusercontent.com/54270298/150631734-7adc288a-4423-41e1-87e8-3b04b6ab1470.png)

**Comment by Majrusz** [comment]
Thanks for reporting that, fixed in 3cdc08ef6af2fee7c171ea4ca2118aca1122c3ce and soon will be available in the next release
