### ISSUE TITLE
Server Crash 1.18.1

### ISSUE THREAD

**Issue by Tyrius1** [Majrusz/MajruszsProgressiveDifficultyMod#86]
https://pastebin.com/fD1V20vM
Hey there got a crash report for ya. Not entirely sure it's even caused by maj difficulty.
Was exploring on my server in creative. Client did not crash but server did.

MC 1.18.1
Forge 39.0.59
majrusz-library-1.18.1-2.7.1
majruszs-difficulty-1.18.1-1.4.1

**Comment by Majrusz** [comment]
Should not be a problem anymore because class that crashed was completely overhauled
