### ISSUE TITLE
New bleeding effect pierce shield

### ISSUE THREAD

**Issue by Ritzumi** [Majrusz/MajruszsProgressiveDifficultyMod#9]
### Versions
Forge: 35.1.36
Majruszs's Difficulty: 1.16.4-0.3.0

### Description
The new effect 'bleeding' can be applied to player even when the hit is negated by shield. Is it intend?  Husk doesn't apply hunger on negated so I am concern a bit @@. 

### How to reproduce
1. Join a world
2. Summon a hostile entity such as zombie
3. Shield up while it attack you
4. Behold~

### Attachment
https://www.loom.com/share/31d3694af3804819a7dc3cd733926bc6

**Comment by Majrusz** [comment]
Hi, thanks for your feedback. This is definitely a bug and will be fixed in the next update.
