### ISSUE TITLE
Gamestate Resets After Leaving Then Rejoining World

### ISSUE THREAD

**Issue by FirmFoundationSoftware** [Majrusz/MajruszsProgressiveDifficultyMod#92]
The gamestate always reverts to whatever is listed in the default_game_state = "NORMAL" line of the config. Basically no matter what gamestate I progress to or set with the /gamestate command, it will always revert to NORMAL upon rejoining the world. If it's set to EXPERT or MASTER the same outcome applies, and upon leaving and rejoining the world it will be EXPERT or MASTER, no matter what I progressed to. 
![Screenshot (1)](https://user-images.githubusercontent.com/102276631/164676877-0c002d30-8856-4902-86a9-02aab7e7982e.png)

**Comment by Majrusz** [comment]
Which version of the mod you are using?
