### ISSUE TITLE
[Request] 1.16.5 Ability to add mobs to the Undead Army

### ISSUE THREAD

**Issue by Zytheus** [Majrusz/MajruszsProgressiveDifficultyMod#94]
I'd like to add mobs from other mods into the Undead Army. Is it possible to allow this?

I have no Java knowledge and do not know how I can successfully edit WaveMember.java

I want to include the mobs from MutantBeasts and MutantMore in the Undead Army's last wave.

It would look something like this in WaveMember.java:

`public enum WaveMember implements IExtensibleEnum {
	ZOMBIE( EntityType.ZOMBIE, 5, 4, 3, 2, 2 ), HUSK( EntityType.HUSK, 1, 1, 2, 4, 5 ), SKELETON(
		EntityType.SKELETON, 3, 3, 2, 2, 2 ), STRAY( EntityType.STRAY, 1, 1, 2, 3, 4 ), ELITE_SKELETON( EliteSkeletonEntity.type, 1, 2, 3, 5, 6 ), MUTANT_ZOMBIE( MBEntityType.MutantZombieEntity, 0, 0, 0, 1, 2);`
		
		
I just don't know anything about how to make two mods work together 

Please include ability to add mobs to army with config

**Comment by Majrusz** [comment]
Hi, unfortunately I do not support older version of my mods. Right now I only focus on the latest Minecraft version and if I remember correctly I added that config in 1.17 or 1.18
