### ISSUE TITLE
Add Config Option to Disable Changes to Hoe Mechanics

### ISSUE THREAD

**Issue by Lonemind** [Majrusz/MajruszsProgressiveDifficultyMod#96]
With ProgressiveDifficulty installed hoes till a 3x3 area of land. It seems to override changes to hoes made by other mods, for instance, Iguana's Tweaks nerfing of the wood/stone hoes.

It'd be great to get a config option that allows the user to either disable the 3x3 tilling all together or pick and choose which hoes it affects for modpacks that wish to make farming more difficult.

**Comment by Majrusz** [comment]
It was a bug and only Enderium Hoe supposed to do that. Anyway thanks for reporting that, fixed here c27ea34581f037babf65a6e20badfb4ac722f5cf and new update will soon be available
