### ISSUE TITLE
[1.19] Breaking changes with Forge 41.0.94+

### ISSUE THREAD

**Issue by Baggytrousers27** [Majrusz/MajruszsProgressiveDifficultyMod#98]
Forge 41.0.98
majrusz-library-1.19-2.10.0
majruszs-difficulty-1.19-1.5.4

[crash-2022-07-15_07.16.32-fml.txt](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/9115534/crash-2022-07-15_07.16.32-fml.txt)

**Comment by Majrusz** [comment]
Thanks for reporting that, fixed here 31dc37f8d098f17664a3d051905780aac564e407 and soon a new update will be available to download
