### ISSUE TITLE
[1.19] Crash on new world with Clickable Advancements

### ISSUE THREAD

**Issue by Baggytrousers27** [Majrusz/MajruszsProgressiveDifficultyMod#99]
Forge 1.19 41.0.106
clickadv-1.19-2.5
majrusz-library-1.19-2.11.0
majruszs-difficulty-1.19-1.5.5

Created a new world and crashed upon loading with this message:

The game crashed whilst exception in server tick loop
Error: java.lang.NoSuchMethodError: 'net.minecraft.world.entity.player.Player net.minecraftforge.event.entity.player.AdvancementEvent.getPlayer()'
Exit Code: -1

[crashlog](https://github.com/Majrusz/MajruszsProgressiveDifficultyMod/files/9164267/crash-2022-07-22_13.05.48-server.txt)

**Comment by Baggytrousers27** [comment]
If clickadv is added after world is created then everything runs as normal.

**Comment by Majrusz** [comment]
Thanks for the report, I see that it was already fixed here https://github.com/someaddons/ClickableAdvancements/issues/11
